package runtime.evaluators.autogenerated;

import java.lang.ref.WeakReference;
import java.util.List;
import java.util.Iterator;

import runtime.evaluators.AtLeastOneConditionEvaluator;
public class FigObjectFlowState_1504945488 extends AtLeastOneConditionEvaluator {
	private Object currentObject;
	private String clsName;

	public FigObjectFlowState_1504945488(String clsName) {
		this.clsName = clsName;
	}

	public void monitor() throws ClassNotFoundException, NumberFormatException {

		currentObject = null;
		//currentObject =	 Class.forName(clsName).cast(currentObject); 
		currentObject = Class.forName(clsName, false,Thread.currentThread().getContextClassLoader()).cast(currentObject); 
 		if ( map.containsKey(clsName)) {
 			List<WeakReference<Object>> objectsList =	 map.get(clsName);
 			for (Iterator<WeakReference<Object>> it = objectsList.iterator();it.hasNext();) {
 				WeakReference<Object> object = it.next();
 				if (object.isEnqueued())
 					addQueuedObject(clsName, object);
 				else {
 					currentObject = object.get();
 					sfh.setCurrentStaticObject(currentObject);
 					fh.setCurrentObject(currentObject);

						String sV19 = expression("nameFig._curText.value[nameFig._curText.offset]","char");
						Character V19 = !sV19.isEmpty() ? parseChar(sV19) : null;
						String sV17 = expression("nameFig._curText.value.length","int");
						Integer V17 = !sV17.isEmpty() ? Integer.parseInt(sV17) : null;
						String sV20 = expression("state._curText.value.length","int");
						Integer V20 = !sV20.isEmpty() ? Integer.parseInt(sV20) : null;
						String sV18 = expression("nameFig._curText.offset","int");
						Integer V18 = !sV18.isEmpty() ? Integer.parseInt(sV18) : null;
						String sV13 = expression("nameFig._curText.count","int");
						Integer V13 = !sV13.isEmpty() ? Integer.parseInt(sV13) : null;
						String sV14 = expression("nameFig._lineSpacing","int");
						Integer V14 = !sV14.isEmpty() ? Integer.parseInt(sV14) : null;
						String sV2 = expression("nameFig._rightMargin","int");
						Integer V2 = !sV2.isEmpty() ? Integer.parseInt(sV2) : null;
						String sV15 = expression("state._curText.count","int");
						Integer V15 = !sV15.isEmpty() ? Integer.parseInt(sV15) : null;
						String sV1 = expression("nameFig._leftMargin","int");
						Integer V1 = !sV1.isEmpty() ? Integer.parseInt(sV1) : null;
						String sV6 = expression("nameFig._botMargin","int");
						Integer V6 = !sV6.isEmpty() ? Integer.parseInt(sV6) : null;
						String sV4 = expression("nameFig._font.size","int");
						Integer V4 = !sV4.isEmpty() ? Integer.parseInt(sV4) : null;
						String sV3 = expression("nameFig._lineWidth","int");
						Integer V3 = !sV3.isEmpty() ? Integer.parseInt(sV3) : null;
						String sV5 = expression("nameFig._topMargin","int");
						Integer V5 = !sV5.isEmpty() ? Integer.parseInt(sV5) : null;
						String sV16 = expression("state._lineSpacing","int");
						Integer V16 = !sV16.isEmpty() ? Integer.parseInt(sV16) : null;
						String sV8 = expression("state._rightMargin","int");
						Integer V8 = !sV8.isEmpty() ? Integer.parseInt(sV8) : null;
						String sV7 = expression("state._leftMargin","int");
						Integer V7 = !sV7.isEmpty() ? Integer.parseInt(sV7) : null;
						String sV12 = expression("state._botMargin","int");
						Integer V12 = !sV12.isEmpty() ? Integer.parseInt(sV12) : null;
						String sV10 = expression("state._font.size","int");
						Integer V10 = !sV10.isEmpty() ? Integer.parseInt(sV10) : null;
						String sV9 = expression("state._lineWidth","int");
						Integer V9 = !sV9.isEmpty() ? Integer.parseInt(sV9) : null;
						String sV11 = expression("state._topMargin","int");
						Integer V11 = !sV11.isEmpty() ? Integer.parseInt(sV11) : null;

						getMinimumSizeFigObjectFlowState_1504945488_52(V6, V1, V2, V3, V4, V5);
						getMinimumSizeFigObjectFlowState_1504945488_60(V6, V7, V8, V9, V10, V12, V11, V1, V2, V3, V4, V5);
						getMinimumSizeFigObjectFlowState_1504945488_14(V6, V14, V13, V1, V2, V3, V4, V5);
						getMinimumSizeFigObjectFlowState_1504945488_30(V15);
						getMinimumSizeFigObjectFlowState_1504945488_43(V7, V8, V9, V10, V16, V15, V1, V2, V3);
						getMinimumSizeFigObjectFlowState_1504945488_56(V6, V7, V8, V9, V10, V12, V11, V1, V2, V3, V4, V5);
						getMinimumSizeFigObjectFlowState_1504945488_73(V6, V1, V2, V3, V4, V5);
						getMinimumSizeFigObjectFlowState_1504945488_54(V6, V1, V2, V3, V4, V5);
						getMinimumSizeFigObjectFlowState_1504945488_70(V6, V7, V8, V9, V12, V11, V1, V2, V3, V4, V5);
						getMinimumSizeFigObjectFlowState_1504945488_28(V15);
						getMinimumSizeFigObjectFlowState_1504945488_2(V13);
						getMinimumSizeFigObjectFlowState_1504945488_4(V13, V18, V17, V19);
						getMinimumSizeFigObjectFlowState_1504945488_36(V7, V8, V9, V10, V16, V15);
						getMinimumSizeFigObjectFlowState_1504945488_37(V7, V8, V9, V10, V12, V11);
						getMinimumSizeFigObjectFlowState_1504945488_48(V7, V8, V9, V16, V15, V1, V2, V3, V4);
						getMinimumSizeFigObjectFlowState_1504945488_21(V14, V13, V1, V2, V3, V4);
						getMinimumSizeFigObjectFlowState_1504945488_15(V7, V8, V9, V14, V13, V1, V2, V3, V4);
						getMinimumSizeFigObjectFlowState_1504945488_22(V6, V14, V13, V1, V2, V3, V4, V5);
						getMinimumSizeFigObjectFlowState_1504945488_26(V15);
						getMinimumSizeFigObjectFlowState_1504945488_65(V6, V7, V8, V9, V12, V11, V1, V2, V3, V4, V5);
						getMinimumSizeFigObjectFlowState_1504945488_74(V6, V1, V2, V3, V4, V5);
						getMinimumSizeFigObjectFlowState_1504945488_32(V7, V8, V9, V10, V12, V11, V16, V15);
						getMinimumSizeFigObjectFlowState_1504945488_69(V6, V7, V8, V9, V12, V11, V1, V2, V3, V4, V5);
						getMinimumSizeFigObjectFlowState_1504945488_16(V7, V8, V9, V14, V13, V1, V2, V3, V4);
						getMinimumSizeFigObjectFlowState_1504945488_53(V6, V1, V2, V3, V4, V5);
						getMinimumSizeFigObjectFlowState_1504945488_67(V6, V7, V8, V9, V12, V11, V1, V2, V3, V4, V5);
						getMinimumSizeFigObjectFlowState_1504945488_10(V14, V13, V15, V4);
						getMinimumSizeFigObjectFlowState_1504945488_3(V13);
						getMinimumSizeFigObjectFlowState_1504945488_5(V13, V18, V17, V19);
						getMinimumSizeFigObjectFlowState_1504945488_13(V6, V14, V13, V1, V2, V3, V4, V5);
						getMinimumSizeFigObjectFlowState_1504945488_61(V6, V7, V8, V9, V10, V12, V11, V1, V2, V3, V4, V5);
						getMinimumSizeFigObjectFlowState_1504945488_6(V13, V17);
						getMinimumSizeFigObjectFlowState_1504945488_18(V14, V13, V15, V4);
						getMinimumSizeFigObjectFlowState_1504945488_33(V7, V8, V9, V10, V16, V15);
						getMinimumSizeFigObjectFlowState_1504945488_45(V7, V8, V9, V16, V15, V1, V2, V3, V4);
						getMinimumSizeFigObjectFlowState_1504945488_47(V7, V8, V9, V16, V15, V1, V2, V3, V4);
						getMinimumSizeFigObjectFlowState_1504945488_57(V6, V7, V8, V9, V10, V12, V11, V1, V2, V3, V4, V5);
						getMinimumSizeFigObjectFlowState_1504945488_25(V7, V8, V9, V14, V13, V1, V2, V3, V4);
						getMinimumSizeFigObjectFlowState_1504945488_72(V6, V1, V2, V3, V4, V5);
						getMinimumSizeFigObjectFlowState_1504945488_59(V6, V7, V8, V9, V10, V12, V11, V1, V2, V3, V4, V5);
						getMinimumSizeFigObjectFlowState_1504945488_8(V14, V13, V4);
						getMinimumSizeFigObjectFlowState_1504945488_49(V6, V1, V2, V3, V4, V5);
						getMinimumSizeFigObjectFlowState_1504945488_40(V7, V8, V9, V10, V12, V11);
						getMinimumSizeFigObjectFlowState_1504945488_62(V6, V7, V8, V9, V10, V12, V11, V1, V2, V3, V4, V5);
						getMinimumSizeFigObjectFlowState_1504945488_0(V13, V17);
						getMinimumSizeFigObjectFlowState_1504945488_1(V13);
						getMinimumSizeFigObjectFlowState_1504945488_68(V6, V7, V8, V9, V12, V11, V1, V2, V3, V4, V5);
						getMinimumSizeFigObjectFlowState_1504945488_24(V7, V8, V9, V14, V13, V1, V2, V3, V4);
						getMinimumSizeFigObjectFlowState_1504945488_31(V7, V8, V9, V10, V12, V11, V16, V15);
						getMinimumSizeFigObjectFlowState_1504945488_46(V7, V8, V9, V16, V15, V1, V2, V3, V4);
						getMinimumSizeFigObjectFlowState_1504945488_58(V6, V7, V8, V9, V10, V12, V11, V1, V2, V3, V4, V5);
						getMinimumSizeFigObjectFlowState_1504945488_12(V14, V13, V1, V2, V3, V4);
						getMinimumSizeFigObjectFlowState_1504945488_34(V7, V8, V9, V10, V12, V11, V16, V15);
						getMinimumSizeFigObjectFlowState_1504945488_35(V7, V8, V9, V10, V12, V11, V16, V15);
						getMinimumSizeFigObjectFlowState_1504945488_38(V7, V8, V9, V10, V12, V11);
						getMinimumSizeFigObjectFlowState_1504945488_71(V6, V1, V2, V3, V4, V5);
						getMinimumSizeFigObjectFlowState_1504945488_11(V14, V13, V1, V2, V3, V4);
						getMinimumSizeFigObjectFlowState_1504945488_41(V7, V8, V9, V10, V16, V15, V1, V2, V3);
						getMinimumSizeFigObjectFlowState_1504945488_51(V6, V1, V2, V3, V4, V5);
						getMinimumSizeFigObjectFlowState_1504945488_55(V6, V7, V8, V9, V10, V12, V11, V1, V2, V3, V4, V5);
						getMinimumSizeFigObjectFlowState_1504945488_23(V6, V14, V13, V1, V2, V3, V4, V5);
						getMinimumSizeFigObjectFlowState_1504945488_20(V14, V13, V1, V2, V3, V4);
						getMinimumSizeFigObjectFlowState_1504945488_64(V6, V7, V8, V9, V12, V11, V1, V2, V3, V4, V5);
						getMinimumSizeFigObjectFlowState_1504945488_42(V7, V8, V9, V10, V16, V15, V1, V2, V3);
						getMinimumSizeFigObjectFlowState_1504945488_63(V6, V7, V8, V9, V12, V11, V1, V2, V3, V4, V5);
						getMinimumSizeFigObjectFlowState_1504945488_44(V7, V8, V9, V10, V16, V15, V1, V2, V3);
						getMinimumSizeFigObjectFlowState_1504945488_9(V14, V13, V15, V4);
						getMinimumSizeFigObjectFlowState_1504945488_17(V14, V13, V4);
						getMinimumSizeFigObjectFlowState_1504945488_7(V13);
						getMinimumSizeFigObjectFlowState_1504945488_27(V15);
						getMinimumSizeFigObjectFlowState_1504945488_29(V20, V15);
						getMinimumSizeFigObjectFlowState_1504945488_19(V14, V13, V15, V4);
						getMinimumSizeFigObjectFlowState_1504945488_66(V6, V7, V8, V9, V12, V11, V1, V2, V3, V4, V5);
						getMinimumSizeFigObjectFlowState_1504945488_50(V6, V1, V2, V3, V4, V5);
						getMinimumSizeFigObjectFlowState_1504945488_39(V7, V8, V9, V10, V12, V11);
				} 
			}
		}
	}

 private void getMinimumSizeFigObjectFlowState_1504945488_52(Integer V6, Integer V1, Integer V2, Integer V3, Integer V4, Integer V5) {

		String pathCondition = "getMinimumSizeFigObjectFlowState_1504945488_52";
		if(V6 == null || V1 == null || V2 == null || V3 == null || V4 == null || V5 == null){
		 Character val = values.get(pathCondition);
		 if (val.equals('U'))
		 values.put(pathCondition, 'U');
		 else if (val.equals('T'))
		 values.put(pathCondition, 'T');
		 else if (val.equals('F'))
		 values.put(pathCondition, 'F');
		} else if (30 + V1 + V2 + 2 * V3 + 16 >= 16 && 30 + V1 + V2 + 2 * V3 + 16 < 35 && V4 + V5 + V6 + 2 * V3 + 8 + 8 + 8 < 25){
		 values.put(pathCondition, 'T');
		} else {
		 Character val = values.get(pathCondition);
		 if (val.equals('F') || val.equals('U'))
		 values.put(pathCondition, 'F');
		 else
		 values.put(pathCondition, 'T');
		}
 }


 private void getMinimumSizeFigObjectFlowState_1504945488_60(Integer V6, Integer V7, Integer V8, Integer V9, Integer V10, Integer V12, Integer V11, Integer V1, Integer V2, Integer V3, Integer V4, Integer V5) {

		String pathCondition = "getMinimumSizeFigObjectFlowState_1504945488_60";
		if(V6 == null || V7 == null || V8 == null || V9 == null || V10 == null || V12 == null || V11 == null || V1 == null || V2 == null || V3 == null || V4 == null || V5 == null){
		 Character val = values.get(pathCondition);
		 if (val.equals('U'))
		 values.put(pathCondition, 'U');
		 else if (val.equals('T'))
		 values.put(pathCondition, 'T');
		 else if (val.equals('F'))
		 values.put(pathCondition, 'F');
		} else if (30 + V1 + V2 + 2 * V3 + 16 < 30 + V7 + V8 + 2 * V9 + 16 && 30 + V7 + V8 + 2 * V9 + 16 >= 35 && V4 + V5 + V6 + 2 * V3 + 8 + 8 + V10 + V11 + V12 + 2 * V9 + 8 < 25){
		 values.put(pathCondition, 'T');
		} else {
		 Character val = values.get(pathCondition);
		 if (val.equals('F') || val.equals('U'))
		 values.put(pathCondition, 'F');
		 else
		 values.put(pathCondition, 'T');
		}
 }


 private void getMinimumSizeFigObjectFlowState_1504945488_14(Integer V6, Integer V14, Integer V13, Integer V1, Integer V2, Integer V3, Integer V4, Integer V5) {

		String pathCondition = "getMinimumSizeFigObjectFlowState_1504945488_14";
		if(V6 == null || V14 == null || V13 == null || V1 == null || V2 == null || V3 == null || V4 == null || V5 == null){
		 Character val = values.get(pathCondition);
		 if (val.equals('U'))
		 values.put(pathCondition, 'U');
		 else if (val.equals('T'))
		 values.put(pathCondition, 'T');
		 else if (val.equals('F'))
		 values.put(pathCondition, 'F');
		} else if (V13 <= 0 && V4 + V14 >= V4 && 30 + V1 + V2 + 2 * V3 + 16 < 16 && V4 + V14 + V5 + V6 + 2 * V3 + 8 + 8 + 8 < 25){
		 values.put(pathCondition, 'T');
		} else {
		 Character val = values.get(pathCondition);
		 if (val.equals('F') || val.equals('U'))
		 values.put(pathCondition, 'F');
		 else
		 values.put(pathCondition, 'T');
		}
 }


 private void getMinimumSizeFigObjectFlowState_1504945488_30(Integer V15) {

		String pathCondition = "getMinimumSizeFigObjectFlowState_1504945488_30";
		if(V15 == null){
		 Character val = values.get(pathCondition);
		 if (val.equals('U'))
		 values.put(pathCondition, 'U');
		 else if (val.equals('T'))
		 values.put(pathCondition, 'T');
		 else if (val.equals('F'))
		 values.put(pathCondition, 'F');
		} else if (V15 > 0){
		 values.put(pathCondition, 'T');
		} else {
		 Character val = values.get(pathCondition);
		 if (val.equals('F') || val.equals('U'))
		 values.put(pathCondition, 'F');
		 else
		 values.put(pathCondition, 'T');
		}
 }


 private void getMinimumSizeFigObjectFlowState_1504945488_43(Integer V7, Integer V8, Integer V9, Integer V10, Integer V16, Integer V15, Integer V1, Integer V2, Integer V3) {

		String pathCondition = "getMinimumSizeFigObjectFlowState_1504945488_43";
		if(V7 == null || V8 == null || V9 == null || V10 == null || V16 == null || V15 == null || V1 == null || V2 == null || V3 == null){
		 Character val = values.get(pathCondition);
		 if (val.equals('U'))
		 values.put(pathCondition, 'U');
		 else if (val.equals('T'))
		 values.put(pathCondition, 'T');
		 else if (val.equals('F'))
		 values.put(pathCondition, 'F');
		} else if (V15 <= 0 && V10 + V16 < V10 && 30 + V1 + V2 + 2 * V3 + 16 >= 30 + V7 + V8 + 2 * V9 + 16){
		 values.put(pathCondition, 'T');
		} else {
		 Character val = values.get(pathCondition);
		 if (val.equals('F') || val.equals('U'))
		 values.put(pathCondition, 'F');
		 else
		 values.put(pathCondition, 'T');
		}
 }


 private void getMinimumSizeFigObjectFlowState_1504945488_56(Integer V6, Integer V7, Integer V8, Integer V9, Integer V10, Integer V12, Integer V11, Integer V1, Integer V2, Integer V3, Integer V4, Integer V5) {

		String pathCondition = "getMinimumSizeFigObjectFlowState_1504945488_56";
		if(V6 == null || V7 == null || V8 == null || V9 == null || V10 == null || V12 == null || V11 == null || V1 == null || V2 == null || V3 == null || V4 == null || V5 == null){
		 Character val = values.get(pathCondition);
		 if (val.equals('U'))
		 values.put(pathCondition, 'U');
		 else if (val.equals('T'))
		 values.put(pathCondition, 'T');
		 else if (val.equals('F'))
		 values.put(pathCondition, 'F');
		} else if (30 + V1 + V2 + 2 * V3 + 16 >= 30 + V7 + V8 + 2 * V9 + 16 && 30 + V1 + V2 + 2 * V3 + 16 >= 35 && V4 + V5 + V6 + 2 * V3 + 8 + 8 + V10 + V11 + V12 + 2 * V9 + 8 < 25){
		 values.put(pathCondition, 'T');
		} else {
		 Character val = values.get(pathCondition);
		 if (val.equals('F') || val.equals('U'))
		 values.put(pathCondition, 'F');
		 else
		 values.put(pathCondition, 'T');
		}
 }


 private void getMinimumSizeFigObjectFlowState_1504945488_73(Integer V6, Integer V1, Integer V2, Integer V3, Integer V4, Integer V5) {

		String pathCondition = "getMinimumSizeFigObjectFlowState_1504945488_73";
		if(V6 == null || V1 == null || V2 == null || V3 == null || V4 == null || V5 == null){
		 Character val = values.get(pathCondition);
		 if (val.equals('U'))
		 values.put(pathCondition, 'U');
		 else if (val.equals('T'))
		 values.put(pathCondition, 'T');
		 else if (val.equals('F'))
		 values.put(pathCondition, 'F');
		} else if (30 + V1 + V2 + 2 * V3 + 16 < 35 && V4 + V5 + V6 + 2 * V3 + 8 + 8 + V4 + V5 + V6 + 2 * V3 + 8 >= 25){
		 values.put(pathCondition, 'T');
		} else {
		 Character val = values.get(pathCondition);
		 if (val.equals('F') || val.equals('U'))
		 values.put(pathCondition, 'F');
		 else
		 values.put(pathCondition, 'T');
		}
 }


 private void getMinimumSizeFigObjectFlowState_1504945488_54(Integer V6, Integer V1, Integer V2, Integer V3, Integer V4, Integer V5) {

		String pathCondition = "getMinimumSizeFigObjectFlowState_1504945488_54";
		if(V6 == null || V1 == null || V2 == null || V3 == null || V4 == null || V5 == null){
		 Character val = values.get(pathCondition);
		 if (val.equals('U'))
		 values.put(pathCondition, 'U');
		 else if (val.equals('T'))
		 values.put(pathCondition, 'T');
		 else if (val.equals('F'))
		 values.put(pathCondition, 'F');
		} else if (30 + V1 + V2 + 2 * V3 + 16 < 16 && V4 + V5 + V6 + 2 * V3 + 8 + 8 + 8 < 25){
		 values.put(pathCondition, 'T');
		} else {
		 Character val = values.get(pathCondition);
		 if (val.equals('F') || val.equals('U'))
		 values.put(pathCondition, 'F');
		 else
		 values.put(pathCondition, 'T');
		}
 }


 private void getMinimumSizeFigObjectFlowState_1504945488_70(Integer V6, Integer V7, Integer V8, Integer V9, Integer V12, Integer V11, Integer V1, Integer V2, Integer V3, Integer V4, Integer V5) {

		String pathCondition = "getMinimumSizeFigObjectFlowState_1504945488_70";
		if(V6 == null || V7 == null || V8 == null || V9 == null || V12 == null || V11 == null || V1 == null || V2 == null || V3 == null || V4 == null || V5 == null){
		 Character val = values.get(pathCondition);
		 if (val.equals('U'))
		 values.put(pathCondition, 'U');
		 else if (val.equals('T'))
		 values.put(pathCondition, 'T');
		 else if (val.equals('F'))
		 values.put(pathCondition, 'F');
		} else if (30 + V1 + V2 + 2 * V3 + 16 < 30 + V7 + V8 + 2 * V9 + 16 && 30 + V7 + V8 + 2 * V9 + 16 < 35 && V4 + V5 + V6 + 2 * V3 + 8 + 8 + V4 + V11 + V12 + 2 * V9 + 8 < 25){
		 values.put(pathCondition, 'T');
		} else {
		 Character val = values.get(pathCondition);
		 if (val.equals('F') || val.equals('U'))
		 values.put(pathCondition, 'F');
		 else
		 values.put(pathCondition, 'T');
		}
 }


 private void getMinimumSizeFigObjectFlowState_1504945488_28(Integer V15) {

		String pathCondition = "getMinimumSizeFigObjectFlowState_1504945488_28";
		if(V15 == null){
		 Character val = values.get(pathCondition);
		 if (val.equals('U'))
		 values.put(pathCondition, 'U');
		 else if (val.equals('T'))
		 values.put(pathCondition, 'T');
		 else if (val.equals('F'))
		 values.put(pathCondition, 'F');
		} else if (V15 < 0){
		 values.put(pathCondition, 'T');
		} else {
		 Character val = values.get(pathCondition);
		 if (val.equals('F') || val.equals('U'))
		 values.put(pathCondition, 'F');
		 else
		 values.put(pathCondition, 'T');
		}
 }


 private void getMinimumSizeFigObjectFlowState_1504945488_2(Integer V13) {

		String pathCondition = "getMinimumSizeFigObjectFlowState_1504945488_2";
		if(V13 == null){
		 Character val = values.get(pathCondition);
		 if (val.equals('U'))
		 values.put(pathCondition, 'U');
		 else if (val.equals('T'))
		 values.put(pathCondition, 'T');
		 else if (val.equals('F'))
		 values.put(pathCondition, 'F');
		} else if (V13 >= 0 && V13 <= 0){
		 values.put(pathCondition, 'T');
		} else {
		 Character val = values.get(pathCondition);
		 if (val.equals('F') || val.equals('U'))
		 values.put(pathCondition, 'F');
		 else
		 values.put(pathCondition, 'T');
		}
 }


 private void getMinimumSizeFigObjectFlowState_1504945488_4(Integer V13, Integer V18, Integer V17, Character V19) {

		String pathCondition = "getMinimumSizeFigObjectFlowState_1504945488_4";
		if(V13 == null || V18 == null || V17 == null || V19 == null){
		 Character val = values.get(pathCondition);
		 if (val.equals('U'))
		 values.put(pathCondition, 'U');
		 else if (val.equals('T'))
		 values.put(pathCondition, 'T');
		 else if (val.equals('F'))
		 values.put(pathCondition, 'F');
		} else if (V13 > 0 && V17 >= 0 && V18 >= 0 && V18 < V17 && V19 <= 13){
		 values.put(pathCondition, 'T');
		} else {
		 Character val = values.get(pathCondition);
		 if (val.equals('F') || val.equals('U'))
		 values.put(pathCondition, 'F');
		 else
		 values.put(pathCondition, 'T');
		}
 }


 private void getMinimumSizeFigObjectFlowState_1504945488_36(Integer V7, Integer V8, Integer V9, Integer V10, Integer V16, Integer V15) {

		String pathCondition = "getMinimumSizeFigObjectFlowState_1504945488_36";
		if(V7 == null || V8 == null || V9 == null || V10 == null || V16 == null || V15 == null){
		 Character val = values.get(pathCondition);
		 if (val.equals('U'))
		 values.put(pathCondition, 'U');
		 else if (val.equals('T'))
		 values.put(pathCondition, 'T');
		 else if (val.equals('F'))
		 values.put(pathCondition, 'F');
		} else if (V15 <= 0 && V10 + V16 < V10 && 16 < 30 + V7 + V8 + 2 * V9 + 16){
		 values.put(pathCondition, 'T');
		} else {
		 Character val = values.get(pathCondition);
		 if (val.equals('F') || val.equals('U'))
		 values.put(pathCondition, 'F');
		 else
		 values.put(pathCondition, 'T');
		}
 }


 private void getMinimumSizeFigObjectFlowState_1504945488_37(Integer V7, Integer V8, Integer V9, Integer V10, Integer V12, Integer V11) {

		String pathCondition = "getMinimumSizeFigObjectFlowState_1504945488_37";
		if(V7 == null || V8 == null || V9 == null || V10 == null || V12 == null || V11 == null){
		 Character val = values.get(pathCondition);
		 if (val.equals('U'))
		 values.put(pathCondition, 'U');
		 else if (val.equals('T'))
		 values.put(pathCondition, 'T');
		 else if (val.equals('F'))
		 values.put(pathCondition, 'F');
		} else if (16 >= 30 + V7 + V8 + 2 * V9 + 16 && 16 + V10 + V11 + V12 + 2 * V9 + 8 >= 25){
		 values.put(pathCondition, 'T');
		} else {
		 Character val = values.get(pathCondition);
		 if (val.equals('F') || val.equals('U'))
		 values.put(pathCondition, 'F');
		 else
		 values.put(pathCondition, 'T');
		}
 }


 private void getMinimumSizeFigObjectFlowState_1504945488_48(Integer V7, Integer V8, Integer V9, Integer V16, Integer V15, Integer V1, Integer V2, Integer V3, Integer V4) {

		String pathCondition = "getMinimumSizeFigObjectFlowState_1504945488_48";
		if(V7 == null || V8 == null || V9 == null || V16 == null || V15 == null || V1 == null || V2 == null || V3 == null || V4 == null){
		 Character val = values.get(pathCondition);
		 if (val.equals('U'))
		 values.put(pathCondition, 'U');
		 else if (val.equals('T'))
		 values.put(pathCondition, 'T');
		 else if (val.equals('F'))
		 values.put(pathCondition, 'F');
		} else if (V15 <= 0 && V4 + V16 < V4 && 30 + V1 + V2 + 2 * V3 + 16 < 30 + V7 + V8 + 2 * V9 + 16){
		 values.put(pathCondition, 'T');
		} else {
		 Character val = values.get(pathCondition);
		 if (val.equals('F') || val.equals('U'))
		 values.put(pathCondition, 'F');
		 else
		 values.put(pathCondition, 'T');
		}
 }


 private void getMinimumSizeFigObjectFlowState_1504945488_21(Integer V14, Integer V13, Integer V1, Integer V2, Integer V3, Integer V4) {

		String pathCondition = "getMinimumSizeFigObjectFlowState_1504945488_21";
		if(V14 == null || V13 == null || V1 == null || V2 == null || V3 == null || V4 == null){
		 Character val = values.get(pathCondition);
		 if (val.equals('U'))
		 values.put(pathCondition, 'U');
		 else if (val.equals('T'))
		 values.put(pathCondition, 'T');
		 else if (val.equals('F'))
		 values.put(pathCondition, 'F');
		} else if (V13 <= 0 && V4 + V14 < V4 && 30 + V1 + V2 + 2 * V3 + 16 >= 16 && 30 + V1 + V2 + 2 * V3 + 16 < 35){
		 values.put(pathCondition, 'T');
		} else {
		 Character val = values.get(pathCondition);
		 if (val.equals('F') || val.equals('U'))
		 values.put(pathCondition, 'F');
		 else
		 values.put(pathCondition, 'T');
		}
 }


 private void getMinimumSizeFigObjectFlowState_1504945488_15(Integer V7, Integer V8, Integer V9, Integer V14, Integer V13, Integer V1, Integer V2, Integer V3, Integer V4) {

		String pathCondition = "getMinimumSizeFigObjectFlowState_1504945488_15";
		if(V7 == null || V8 == null || V9 == null || V14 == null || V13 == null || V1 == null || V2 == null || V3 == null || V4 == null){
		 Character val = values.get(pathCondition);
		 if (val.equals('U'))
		 values.put(pathCondition, 'U');
		 else if (val.equals('T'))
		 values.put(pathCondition, 'T');
		 else if (val.equals('F'))
		 values.put(pathCondition, 'F');
		} else if (V13 <= 0 && V4 + V14 >= V4 && 30 + V1 + V2 + 2 * V3 + 16 >= 30 + V7 + V8 + 2 * V9 + 16){
		 values.put(pathCondition, 'T');
		} else {
		 Character val = values.get(pathCondition);
		 if (val.equals('F') || val.equals('U'))
		 values.put(pathCondition, 'F');
		 else
		 values.put(pathCondition, 'T');
		}
 }


 private void getMinimumSizeFigObjectFlowState_1504945488_22(Integer V6, Integer V14, Integer V13, Integer V1, Integer V2, Integer V3, Integer V4, Integer V5) {

		String pathCondition = "getMinimumSizeFigObjectFlowState_1504945488_22";
		if(V6 == null || V14 == null || V13 == null || V1 == null || V2 == null || V3 == null || V4 == null || V5 == null){
		 Character val = values.get(pathCondition);
		 if (val.equals('U'))
		 values.put(pathCondition, 'U');
		 else if (val.equals('T'))
		 values.put(pathCondition, 'T');
		 else if (val.equals('F'))
		 values.put(pathCondition, 'F');
		} else if (V13 <= 0 && V4 + V14 < V4 && 30 + V1 + V2 + 2 * V3 + 16 < 16 && V4 + V5 + V6 + 2 * V3 + 8 + 8 + 8 >= 25){
		 values.put(pathCondition, 'T');
		} else {
		 Character val = values.get(pathCondition);
		 if (val.equals('F') || val.equals('U'))
		 values.put(pathCondition, 'F');
		 else
		 values.put(pathCondition, 'T');
		}
 }


 private void getMinimumSizeFigObjectFlowState_1504945488_26(Integer V15) {

		String pathCondition = "getMinimumSizeFigObjectFlowState_1504945488_26";
		if(V15 == null){
		 Character val = values.get(pathCondition);
		 if (val.equals('U'))
		 values.put(pathCondition, 'U');
		 else if (val.equals('T'))
		 values.put(pathCondition, 'T');
		 else if (val.equals('F'))
		 values.put(pathCondition, 'F');
		} else if (V15 >= 0 && V15 > 0){
		 values.put(pathCondition, 'T');
		} else {
		 Character val = values.get(pathCondition);
		 if (val.equals('F') || val.equals('U'))
		 values.put(pathCondition, 'F');
		 else
		 values.put(pathCondition, 'T');
		}
 }


 private void getMinimumSizeFigObjectFlowState_1504945488_65(Integer V6, Integer V7, Integer V8, Integer V9, Integer V12, Integer V11, Integer V1, Integer V2, Integer V3, Integer V4, Integer V5) {

		String pathCondition = "getMinimumSizeFigObjectFlowState_1504945488_65";
		if(V6 == null || V7 == null || V8 == null || V9 == null || V12 == null || V11 == null || V1 == null || V2 == null || V3 == null || V4 == null || V5 == null){
		 Character val = values.get(pathCondition);
		 if (val.equals('U'))
		 values.put(pathCondition, 'U');
		 else if (val.equals('T'))
		 values.put(pathCondition, 'T');
		 else if (val.equals('F'))
		 values.put(pathCondition, 'F');
		} else if (30 + V1 + V2 + 2 * V3 + 16 >= 30 + V7 + V8 + 2 * V9 + 16 && 30 + V1 + V2 + 2 * V3 + 16 < 35 && V4 + V5 + V6 + 2 * V3 + 8 + 8 + V4 + V11 + V12 + 2 * V9 + 8 >= 25){
		 values.put(pathCondition, 'T');
		} else {
		 Character val = values.get(pathCondition);
		 if (val.equals('F') || val.equals('U'))
		 values.put(pathCondition, 'F');
		 else
		 values.put(pathCondition, 'T');
		}
 }


 private void getMinimumSizeFigObjectFlowState_1504945488_74(Integer V6, Integer V1, Integer V2, Integer V3, Integer V4, Integer V5) {

		String pathCondition = "getMinimumSizeFigObjectFlowState_1504945488_74";
		if(V6 == null || V1 == null || V2 == null || V3 == null || V4 == null || V5 == null){
		 Character val = values.get(pathCondition);
		 if (val.equals('U'))
		 values.put(pathCondition, 'U');
		 else if (val.equals('T'))
		 values.put(pathCondition, 'T');
		 else if (val.equals('F'))
		 values.put(pathCondition, 'F');
		} else if (30 + V1 + V2 + 2 * V3 + 16 < 35 && V4 + V5 + V6 + 2 * V3 + 8 + 8 + V4 + V5 + V6 + 2 * V3 + 8 < 25){
		 values.put(pathCondition, 'T');
		} else {
		 Character val = values.get(pathCondition);
		 if (val.equals('F') || val.equals('U'))
		 values.put(pathCondition, 'F');
		 else
		 values.put(pathCondition, 'T');
		}
 }


 private void getMinimumSizeFigObjectFlowState_1504945488_32(Integer V7, Integer V8, Integer V9, Integer V10, Integer V12, Integer V11, Integer V16, Integer V15) {

		String pathCondition = "getMinimumSizeFigObjectFlowState_1504945488_32";
		if(V7 == null || V8 == null || V9 == null || V10 == null || V12 == null || V11 == null || V16 == null || V15 == null){
		 Character val = values.get(pathCondition);
		 if (val.equals('U'))
		 values.put(pathCondition, 'U');
		 else if (val.equals('T'))
		 values.put(pathCondition, 'T');
		 else if (val.equals('F'))
		 values.put(pathCondition, 'F');
		} else if (V15 <= 0 && V10 + V16 >= V10 && 16 >= 30 + V7 + V8 + 2 * V9 + 16 && 16 + V10 + V16 + V11 + V12 + 2 * V9 + 8 < 25){
		 values.put(pathCondition, 'T');
		} else {
		 Character val = values.get(pathCondition);
		 if (val.equals('F') || val.equals('U'))
		 values.put(pathCondition, 'F');
		 else
		 values.put(pathCondition, 'T');
		}
 }


 private void getMinimumSizeFigObjectFlowState_1504945488_69(Integer V6, Integer V7, Integer V8, Integer V9, Integer V12, Integer V11, Integer V1, Integer V2, Integer V3, Integer V4, Integer V5) {

		String pathCondition = "getMinimumSizeFigObjectFlowState_1504945488_69";
		if(V6 == null || V7 == null || V8 == null || V9 == null || V12 == null || V11 == null || V1 == null || V2 == null || V3 == null || V4 == null || V5 == null){
		 Character val = values.get(pathCondition);
		 if (val.equals('U'))
		 values.put(pathCondition, 'U');
		 else if (val.equals('T'))
		 values.put(pathCondition, 'T');
		 else if (val.equals('F'))
		 values.put(pathCondition, 'F');
		} else if (30 + V1 + V2 + 2 * V3 + 16 < 30 + V7 + V8 + 2 * V9 + 16 && 30 + V7 + V8 + 2 * V9 + 16 < 35 && V4 + V5 + V6 + 2 * V3 + 8 + 8 + V4 + V11 + V12 + 2 * V9 + 8 >= 25){
		 values.put(pathCondition, 'T');
		} else {
		 Character val = values.get(pathCondition);
		 if (val.equals('F') || val.equals('U'))
		 values.put(pathCondition, 'F');
		 else
		 values.put(pathCondition, 'T');
		}
 }


 private void getMinimumSizeFigObjectFlowState_1504945488_16(Integer V7, Integer V8, Integer V9, Integer V14, Integer V13, Integer V1, Integer V2, Integer V3, Integer V4) {

		String pathCondition = "getMinimumSizeFigObjectFlowState_1504945488_16";
		if(V7 == null || V8 == null || V9 == null || V14 == null || V13 == null || V1 == null || V2 == null || V3 == null || V4 == null){
		 Character val = values.get(pathCondition);
		 if (val.equals('U'))
		 values.put(pathCondition, 'U');
		 else if (val.equals('T'))
		 values.put(pathCondition, 'T');
		 else if (val.equals('F'))
		 values.put(pathCondition, 'F');
		} else if (V13 <= 0 && V4 + V14 >= V4 && 30 + V1 + V2 + 2 * V3 + 16 < 30 + V7 + V8 + 2 * V9 + 16){
		 values.put(pathCondition, 'T');
		} else {
		 Character val = values.get(pathCondition);
		 if (val.equals('F') || val.equals('U'))
		 values.put(pathCondition, 'F');
		 else
		 values.put(pathCondition, 'T');
		}
 }


 private void getMinimumSizeFigObjectFlowState_1504945488_53(Integer V6, Integer V1, Integer V2, Integer V3, Integer V4, Integer V5) {

		String pathCondition = "getMinimumSizeFigObjectFlowState_1504945488_53";
		if(V6 == null || V1 == null || V2 == null || V3 == null || V4 == null || V5 == null){
		 Character val = values.get(pathCondition);
		 if (val.equals('U'))
		 values.put(pathCondition, 'U');
		 else if (val.equals('T'))
		 values.put(pathCondition, 'T');
		 else if (val.equals('F'))
		 values.put(pathCondition, 'F');
		} else if (30 + V1 + V2 + 2 * V3 + 16 < 16 && V4 + V5 + V6 + 2 * V3 + 8 + 8 + 8 >= 25){
		 values.put(pathCondition, 'T');
		} else {
		 Character val = values.get(pathCondition);
		 if (val.equals('F') || val.equals('U'))
		 values.put(pathCondition, 'F');
		 else
		 values.put(pathCondition, 'T');
		}
 }


 private void getMinimumSizeFigObjectFlowState_1504945488_67(Integer V6, Integer V7, Integer V8, Integer V9, Integer V12, Integer V11, Integer V1, Integer V2, Integer V3, Integer V4, Integer V5) {

		String pathCondition = "getMinimumSizeFigObjectFlowState_1504945488_67";
		if(V6 == null || V7 == null || V8 == null || V9 == null || V12 == null || V11 == null || V1 == null || V2 == null || V3 == null || V4 == null || V5 == null){
		 Character val = values.get(pathCondition);
		 if (val.equals('U'))
		 values.put(pathCondition, 'U');
		 else if (val.equals('T'))
		 values.put(pathCondition, 'T');
		 else if (val.equals('F'))
		 values.put(pathCondition, 'F');
		} else if (30 + V1 + V2 + 2 * V3 + 16 < 30 + V7 + V8 + 2 * V9 + 16 && 30 + V7 + V8 + 2 * V9 + 16 >= 35 && V4 + V5 + V6 + 2 * V3 + 8 + 8 + V4 + V11 + V12 + 2 * V9 + 8 >= 25){
		 values.put(pathCondition, 'T');
		} else {
		 Character val = values.get(pathCondition);
		 if (val.equals('F') || val.equals('U'))
		 values.put(pathCondition, 'F');
		 else
		 values.put(pathCondition, 'T');
		}
 }


 private void getMinimumSizeFigObjectFlowState_1504945488_10(Integer V14, Integer V13, Integer V15, Integer V4) {

		String pathCondition = "getMinimumSizeFigObjectFlowState_1504945488_10";
		if(V14 == null || V13 == null || V15 == null || V4 == null){
		 Character val = values.get(pathCondition);
		 if (val.equals('U'))
		 values.put(pathCondition, 'U');
		 else if (val.equals('T'))
		 values.put(pathCondition, 'T');
		 else if (val.equals('F'))
		 values.put(pathCondition, 'F');
		} else if (V13 <= 0 && V4 + V14 >= V4 && V15 <= 0){
		 values.put(pathCondition, 'T');
		} else {
		 Character val = values.get(pathCondition);
		 if (val.equals('F') || val.equals('U'))
		 values.put(pathCondition, 'F');
		 else
		 values.put(pathCondition, 'T');
		}
 }


 private void getMinimumSizeFigObjectFlowState_1504945488_3(Integer V13) {

		String pathCondition = "getMinimumSizeFigObjectFlowState_1504945488_3";
		if(V13 == null){
		 Character val = values.get(pathCondition);
		 if (val.equals('U'))
		 values.put(pathCondition, 'U');
		 else if (val.equals('T'))
		 values.put(pathCondition, 'T');
		 else if (val.equals('F'))
		 values.put(pathCondition, 'F');
		} else if (V13 < 0){
		 values.put(pathCondition, 'T');
		} else {
		 Character val = values.get(pathCondition);
		 if (val.equals('F') || val.equals('U'))
		 values.put(pathCondition, 'F');
		 else
		 values.put(pathCondition, 'T');
		}
 }


 private void getMinimumSizeFigObjectFlowState_1504945488_5(Integer V13, Integer V18, Integer V17, Character V19) {

		String pathCondition = "getMinimumSizeFigObjectFlowState_1504945488_5";
		if(V13 == null || V18 == null || V17 == null || V19 == null){
		 Character val = values.get(pathCondition);
		 if (val.equals('U'))
		 values.put(pathCondition, 'U');
		 else if (val.equals('T'))
		 values.put(pathCondition, 'T');
		 else if (val.equals('F'))
		 values.put(pathCondition, 'F');
		} else if (V13 > 0 && V17 >= 0 && V18 >= 0 && V18 < V17 && V19 > 13){
		 values.put(pathCondition, 'T');
		} else {
		 Character val = values.get(pathCondition);
		 if (val.equals('F') || val.equals('U'))
		 values.put(pathCondition, 'F');
		 else
		 values.put(pathCondition, 'T');
		}
 }


 private void getMinimumSizeFigObjectFlowState_1504945488_13(Integer V6, Integer V14, Integer V13, Integer V1, Integer V2, Integer V3, Integer V4, Integer V5) {

		String pathCondition = "getMinimumSizeFigObjectFlowState_1504945488_13";
		if(V6 == null || V14 == null || V13 == null || V1 == null || V2 == null || V3 == null || V4 == null || V5 == null){
		 Character val = values.get(pathCondition);
		 if (val.equals('U'))
		 values.put(pathCondition, 'U');
		 else if (val.equals('T'))
		 values.put(pathCondition, 'T');
		 else if (val.equals('F'))
		 values.put(pathCondition, 'F');
		} else if (V13 <= 0 && V4 + V14 >= V4 && 30 + V1 + V2 + 2 * V3 + 16 < 16 && V4 + V14 + V5 + V6 + 2 * V3 + 8 + 8 + 8 >= 25){
		 values.put(pathCondition, 'T');
		} else {
		 Character val = values.get(pathCondition);
		 if (val.equals('F') || val.equals('U'))
		 values.put(pathCondition, 'F');
		 else
		 values.put(pathCondition, 'T');
		}
 }


 private void getMinimumSizeFigObjectFlowState_1504945488_61(Integer V6, Integer V7, Integer V8, Integer V9, Integer V10, Integer V12, Integer V11, Integer V1, Integer V2, Integer V3, Integer V4, Integer V5) {

		String pathCondition = "getMinimumSizeFigObjectFlowState_1504945488_61";
		if(V6 == null || V7 == null || V8 == null || V9 == null || V10 == null || V12 == null || V11 == null || V1 == null || V2 == null || V3 == null || V4 == null || V5 == null){
		 Character val = values.get(pathCondition);
		 if (val.equals('U'))
		 values.put(pathCondition, 'U');
		 else if (val.equals('T'))
		 values.put(pathCondition, 'T');
		 else if (val.equals('F'))
		 values.put(pathCondition, 'F');
		} else if (30 + V1 + V2 + 2 * V3 + 16 < 30 + V7 + V8 + 2 * V9 + 16 && 30 + V7 + V8 + 2 * V9 + 16 < 35 && V4 + V5 + V6 + 2 * V3 + 8 + 8 + V10 + V11 + V12 + 2 * V9 + 8 >= 25){
		 values.put(pathCondition, 'T');
		} else {
		 Character val = values.get(pathCondition);
		 if (val.equals('F') || val.equals('U'))
		 values.put(pathCondition, 'F');
		 else
		 values.put(pathCondition, 'T');
		}
 }


 private void getMinimumSizeFigObjectFlowState_1504945488_6(Integer V13, Integer V17) {

		String pathCondition = "getMinimumSizeFigObjectFlowState_1504945488_6";
		if(V13 == null || V17 == null){
		 Character val = values.get(pathCondition);
		 if (val.equals('U'))
		 values.put(pathCondition, 'U');
		 else if (val.equals('T'))
		 values.put(pathCondition, 'T');
		 else if (val.equals('F'))
		 values.put(pathCondition, 'F');
		} else if (V13 > 0 && V17 >= 0){
		 values.put(pathCondition, 'T');
		} else {
		 Character val = values.get(pathCondition);
		 if (val.equals('F') || val.equals('U'))
		 values.put(pathCondition, 'F');
		 else
		 values.put(pathCondition, 'T');
		}
 }


 private void getMinimumSizeFigObjectFlowState_1504945488_18(Integer V14, Integer V13, Integer V15, Integer V4) {

		String pathCondition = "getMinimumSizeFigObjectFlowState_1504945488_18";
		if(V14 == null || V13 == null || V15 == null || V4 == null){
		 Character val = values.get(pathCondition);
		 if (val.equals('U'))
		 values.put(pathCondition, 'U');
		 else if (val.equals('T'))
		 values.put(pathCondition, 'T');
		 else if (val.equals('F'))
		 values.put(pathCondition, 'F');
		} else if (V13 <= 0 && V4 + V14 < V4 && V15 > 0){
		 values.put(pathCondition, 'T');
		} else {
		 Character val = values.get(pathCondition);
		 if (val.equals('F') || val.equals('U'))
		 values.put(pathCondition, 'F');
		 else
		 values.put(pathCondition, 'T');
		}
 }


 private void getMinimumSizeFigObjectFlowState_1504945488_33(Integer V7, Integer V8, Integer V9, Integer V10, Integer V16, Integer V15) {

		String pathCondition = "getMinimumSizeFigObjectFlowState_1504945488_33";
		if(V7 == null || V8 == null || V9 == null || V10 == null || V16 == null || V15 == null){
		 Character val = values.get(pathCondition);
		 if (val.equals('U'))
		 values.put(pathCondition, 'U');
		 else if (val.equals('T'))
		 values.put(pathCondition, 'T');
		 else if (val.equals('F'))
		 values.put(pathCondition, 'F');
		} else if (V15 <= 0 && V10 + V16 >= V10 && 16 < 30 + V7 + V8 + 2 * V9 + 16){
		 values.put(pathCondition, 'T');
		} else {
		 Character val = values.get(pathCondition);
		 if (val.equals('F') || val.equals('U'))
		 values.put(pathCondition, 'F');
		 else
		 values.put(pathCondition, 'T');
		}
 }


 private void getMinimumSizeFigObjectFlowState_1504945488_45(Integer V7, Integer V8, Integer V9, Integer V16, Integer V15, Integer V1, Integer V2, Integer V3, Integer V4) {

		String pathCondition = "getMinimumSizeFigObjectFlowState_1504945488_45";
		if(V7 == null || V8 == null || V9 == null || V16 == null || V15 == null || V1 == null || V2 == null || V3 == null || V4 == null){
		 Character val = values.get(pathCondition);
		 if (val.equals('U'))
		 values.put(pathCondition, 'U');
		 else if (val.equals('T'))
		 values.put(pathCondition, 'T');
		 else if (val.equals('F'))
		 values.put(pathCondition, 'F');
		} else if (V15 <= 0 && V4 + V16 >= V4 && 30 + V1 + V2 + 2 * V3 + 16 >= 30 + V7 + V8 + 2 * V9 + 16){
		 values.put(pathCondition, 'T');
		} else {
		 Character val = values.get(pathCondition);
		 if (val.equals('F') || val.equals('U'))
		 values.put(pathCondition, 'F');
		 else
		 values.put(pathCondition, 'T');
		}
 }


 private void getMinimumSizeFigObjectFlowState_1504945488_47(Integer V7, Integer V8, Integer V9, Integer V16, Integer V15, Integer V1, Integer V2, Integer V3, Integer V4) {

		String pathCondition = "getMinimumSizeFigObjectFlowState_1504945488_47";
		if(V7 == null || V8 == null || V9 == null || V16 == null || V15 == null || V1 == null || V2 == null || V3 == null || V4 == null){
		 Character val = values.get(pathCondition);
		 if (val.equals('U'))
		 values.put(pathCondition, 'U');
		 else if (val.equals('T'))
		 values.put(pathCondition, 'T');
		 else if (val.equals('F'))
		 values.put(pathCondition, 'F');
		} else if (V15 <= 0 && V4 + V16 < V4 && 30 + V1 + V2 + 2 * V3 + 16 >= 30 + V7 + V8 + 2 * V9 + 16){
		 values.put(pathCondition, 'T');
		} else {
		 Character val = values.get(pathCondition);
		 if (val.equals('F') || val.equals('U'))
		 values.put(pathCondition, 'F');
		 else
		 values.put(pathCondition, 'T');
		}
 }


 private void getMinimumSizeFigObjectFlowState_1504945488_57(Integer V6, Integer V7, Integer V8, Integer V9, Integer V10, Integer V12, Integer V11, Integer V1, Integer V2, Integer V3, Integer V4, Integer V5) {

		String pathCondition = "getMinimumSizeFigObjectFlowState_1504945488_57";
		if(V6 == null || V7 == null || V8 == null || V9 == null || V10 == null || V12 == null || V11 == null || V1 == null || V2 == null || V3 == null || V4 == null || V5 == null){
		 Character val = values.get(pathCondition);
		 if (val.equals('U'))
		 values.put(pathCondition, 'U');
		 else if (val.equals('T'))
		 values.put(pathCondition, 'T');
		 else if (val.equals('F'))
		 values.put(pathCondition, 'F');
		} else if (30 + V1 + V2 + 2 * V3 + 16 >= 30 + V7 + V8 + 2 * V9 + 16 && 30 + V1 + V2 + 2 * V3 + 16 < 35 && V4 + V5 + V6 + 2 * V3 + 8 + 8 + V10 + V11 + V12 + 2 * V9 + 8 >= 25){
		 values.put(pathCondition, 'T');
		} else {
		 Character val = values.get(pathCondition);
		 if (val.equals('F') || val.equals('U'))
		 values.put(pathCondition, 'F');
		 else
		 values.put(pathCondition, 'T');
		}
 }


 private void getMinimumSizeFigObjectFlowState_1504945488_25(Integer V7, Integer V8, Integer V9, Integer V14, Integer V13, Integer V1, Integer V2, Integer V3, Integer V4) {

		String pathCondition = "getMinimumSizeFigObjectFlowState_1504945488_25";
		if(V7 == null || V8 == null || V9 == null || V14 == null || V13 == null || V1 == null || V2 == null || V3 == null || V4 == null){
		 Character val = values.get(pathCondition);
		 if (val.equals('U'))
		 values.put(pathCondition, 'U');
		 else if (val.equals('T'))
		 values.put(pathCondition, 'T');
		 else if (val.equals('F'))
		 values.put(pathCondition, 'F');
		} else if (V13 <= 0 && V4 + V14 < V4 && 30 + V1 + V2 + 2 * V3 + 16 < 30 + V7 + V8 + 2 * V9 + 16){
		 values.put(pathCondition, 'T');
		} else {
		 Character val = values.get(pathCondition);
		 if (val.equals('F') || val.equals('U'))
		 values.put(pathCondition, 'F');
		 else
		 values.put(pathCondition, 'T');
		}
 }


 private void getMinimumSizeFigObjectFlowState_1504945488_72(Integer V6, Integer V1, Integer V2, Integer V3, Integer V4, Integer V5) {

		String pathCondition = "getMinimumSizeFigObjectFlowState_1504945488_72";
		if(V6 == null || V1 == null || V2 == null || V3 == null || V4 == null || V5 == null){
		 Character val = values.get(pathCondition);
		 if (val.equals('U'))
		 values.put(pathCondition, 'U');
		 else if (val.equals('T'))
		 values.put(pathCondition, 'T');
		 else if (val.equals('F'))
		 values.put(pathCondition, 'F');
		} else if (30 + V1 + V2 + 2 * V3 + 16 >= 35 && V4 + V5 + V6 + 2 * V3 + 8 + 8 + V4 + V5 + V6 + 2 * V3 + 8 < 25){
		 values.put(pathCondition, 'T');
		} else {
		 Character val = values.get(pathCondition);
		 if (val.equals('F') || val.equals('U'))
		 values.put(pathCondition, 'F');
		 else
		 values.put(pathCondition, 'T');
		}
 }


 private void getMinimumSizeFigObjectFlowState_1504945488_59(Integer V6, Integer V7, Integer V8, Integer V9, Integer V10, Integer V12, Integer V11, Integer V1, Integer V2, Integer V3, Integer V4, Integer V5) {

		String pathCondition = "getMinimumSizeFigObjectFlowState_1504945488_59";
		if(V6 == null || V7 == null || V8 == null || V9 == null || V10 == null || V12 == null || V11 == null || V1 == null || V2 == null || V3 == null || V4 == null || V5 == null){
		 Character val = values.get(pathCondition);
		 if (val.equals('U'))
		 values.put(pathCondition, 'U');
		 else if (val.equals('T'))
		 values.put(pathCondition, 'T');
		 else if (val.equals('F'))
		 values.put(pathCondition, 'F');
		} else if (30 + V1 + V2 + 2 * V3 + 16 < 30 + V7 + V8 + 2 * V9 + 16 && 30 + V7 + V8 + 2 * V9 + 16 >= 35 && V4 + V5 + V6 + 2 * V3 + 8 + 8 + V10 + V11 + V12 + 2 * V9 + 8 >= 25){
		 values.put(pathCondition, 'T');
		} else {
		 Character val = values.get(pathCondition);
		 if (val.equals('F') || val.equals('U'))
		 values.put(pathCondition, 'F');
		 else
		 values.put(pathCondition, 'T');
		}
 }


 private void getMinimumSizeFigObjectFlowState_1504945488_8(Integer V14, Integer V13, Integer V4) {

		String pathCondition = "getMinimumSizeFigObjectFlowState_1504945488_8";
		if(V14 == null || V13 == null || V4 == null){
		 Character val = values.get(pathCondition);
		 if (val.equals('U'))
		 values.put(pathCondition, 'U');
		 else if (val.equals('T'))
		 values.put(pathCondition, 'T');
		 else if (val.equals('F'))
		 values.put(pathCondition, 'F');
		} else if (V13 <= 0 && V4 + V14 >= V4){
		 values.put(pathCondition, 'T');
		} else {
		 Character val = values.get(pathCondition);
		 if (val.equals('F') || val.equals('U'))
		 values.put(pathCondition, 'F');
		 else
		 values.put(pathCondition, 'T');
		}
 }


 private void getMinimumSizeFigObjectFlowState_1504945488_49(Integer V6, Integer V1, Integer V2, Integer V3, Integer V4, Integer V5) {

		String pathCondition = "getMinimumSizeFigObjectFlowState_1504945488_49";
		if(V6 == null || V1 == null || V2 == null || V3 == null || V4 == null || V5 == null){
		 Character val = values.get(pathCondition);
		 if (val.equals('U'))
		 values.put(pathCondition, 'U');
		 else if (val.equals('T'))
		 values.put(pathCondition, 'T');
		 else if (val.equals('F'))
		 values.put(pathCondition, 'F');
		} else if (30 + V1 + V2 + 2 * V3 + 16 >= 16 && 30 + V1 + V2 + 2 * V3 + 16 >= 35 && V4 + V5 + V6 + 2 * V3 + 8 + 8 + 8 >= 25){
		 values.put(pathCondition, 'T');
		} else {
		 Character val = values.get(pathCondition);
		 if (val.equals('F') || val.equals('U'))
		 values.put(pathCondition, 'F');
		 else
		 values.put(pathCondition, 'T');
		}
 }


 private void getMinimumSizeFigObjectFlowState_1504945488_40(Integer V7, Integer V8, Integer V9, Integer V10, Integer V12, Integer V11) {

		String pathCondition = "getMinimumSizeFigObjectFlowState_1504945488_40";
		if(V7 == null || V8 == null || V9 == null || V10 == null || V12 == null || V11 == null){
		 Character val = values.get(pathCondition);
		 if (val.equals('U'))
		 values.put(pathCondition, 'U');
		 else if (val.equals('T'))
		 values.put(pathCondition, 'T');
		 else if (val.equals('F'))
		 values.put(pathCondition, 'F');
		} else if (16 < 30 + V7 + V8 + 2 * V9 + 16 && 16 + V10 + V11 + V12 + 2 * V9 + 8 < 25){
		 values.put(pathCondition, 'T');
		} else {
		 Character val = values.get(pathCondition);
		 if (val.equals('F') || val.equals('U'))
		 values.put(pathCondition, 'F');
		 else
		 values.put(pathCondition, 'T');
		}
 }


 private void getMinimumSizeFigObjectFlowState_1504945488_62(Integer V6, Integer V7, Integer V8, Integer V9, Integer V10, Integer V12, Integer V11, Integer V1, Integer V2, Integer V3, Integer V4, Integer V5) {

		String pathCondition = "getMinimumSizeFigObjectFlowState_1504945488_62";
		if(V6 == null || V7 == null || V8 == null || V9 == null || V10 == null || V12 == null || V11 == null || V1 == null || V2 == null || V3 == null || V4 == null || V5 == null){
		 Character val = values.get(pathCondition);
		 if (val.equals('U'))
		 values.put(pathCondition, 'U');
		 else if (val.equals('T'))
		 values.put(pathCondition, 'T');
		 else if (val.equals('F'))
		 values.put(pathCondition, 'F');
		} else if (30 + V1 + V2 + 2 * V3 + 16 < 30 + V7 + V8 + 2 * V9 + 16 && 30 + V7 + V8 + 2 * V9 + 16 < 35 && V4 + V5 + V6 + 2 * V3 + 8 + 8 + V10 + V11 + V12 + 2 * V9 + 8 < 25){
		 values.put(pathCondition, 'T');
		} else {
		 Character val = values.get(pathCondition);
		 if (val.equals('F') || val.equals('U'))
		 values.put(pathCondition, 'F');
		 else
		 values.put(pathCondition, 'T');
		}
 }


 private void getMinimumSizeFigObjectFlowState_1504945488_0(Integer V13, Integer V17) {

		String pathCondition = "getMinimumSizeFigObjectFlowState_1504945488_0";
		if(V13 == null || V17 == null){
		 Character val = values.get(pathCondition);
		 if (val.equals('U'))
		 values.put(pathCondition, 'U');
		 else if (val.equals('T'))
		 values.put(pathCondition, 'T');
		 else if (val.equals('F'))
		 values.put(pathCondition, 'F');
		} else if (V13 >= 0 && V13 > 0 && V17 >= 0){
		 values.put(pathCondition, 'T');
		} else {
		 Character val = values.get(pathCondition);
		 if (val.equals('F') || val.equals('U'))
		 values.put(pathCondition, 'F');
		 else
		 values.put(pathCondition, 'T');
		}
 }


 private void getMinimumSizeFigObjectFlowState_1504945488_1(Integer V13) {

		String pathCondition = "getMinimumSizeFigObjectFlowState_1504945488_1";
		if(V13 == null){
		 Character val = values.get(pathCondition);
		 if (val.equals('U'))
		 values.put(pathCondition, 'U');
		 else if (val.equals('T'))
		 values.put(pathCondition, 'T');
		 else if (val.equals('F'))
		 values.put(pathCondition, 'F');
		} else if (V13 >= 0 && V13 > 0){
		 values.put(pathCondition, 'T');
		} else {
		 Character val = values.get(pathCondition);
		 if (val.equals('F') || val.equals('U'))
		 values.put(pathCondition, 'F');
		 else
		 values.put(pathCondition, 'T');
		}
 }


 private void getMinimumSizeFigObjectFlowState_1504945488_68(Integer V6, Integer V7, Integer V8, Integer V9, Integer V12, Integer V11, Integer V1, Integer V2, Integer V3, Integer V4, Integer V5) {

		String pathCondition = "getMinimumSizeFigObjectFlowState_1504945488_68";
		if(V6 == null || V7 == null || V8 == null || V9 == null || V12 == null || V11 == null || V1 == null || V2 == null || V3 == null || V4 == null || V5 == null){
		 Character val = values.get(pathCondition);
		 if (val.equals('U'))
		 values.put(pathCondition, 'U');
		 else if (val.equals('T'))
		 values.put(pathCondition, 'T');
		 else if (val.equals('F'))
		 values.put(pathCondition, 'F');
		} else if (30 + V1 + V2 + 2 * V3 + 16 < 30 + V7 + V8 + 2 * V9 + 16 && 30 + V7 + V8 + 2 * V9 + 16 >= 35 && V4 + V5 + V6 + 2 * V3 + 8 + 8 + V4 + V11 + V12 + 2 * V9 + 8 < 25){
		 values.put(pathCondition, 'T');
		} else {
		 Character val = values.get(pathCondition);
		 if (val.equals('F') || val.equals('U'))
		 values.put(pathCondition, 'F');
		 else
		 values.put(pathCondition, 'T');
		}
 }


 private void getMinimumSizeFigObjectFlowState_1504945488_24(Integer V7, Integer V8, Integer V9, Integer V14, Integer V13, Integer V1, Integer V2, Integer V3, Integer V4) {

		String pathCondition = "getMinimumSizeFigObjectFlowState_1504945488_24";
		if(V7 == null || V8 == null || V9 == null || V14 == null || V13 == null || V1 == null || V2 == null || V3 == null || V4 == null){
		 Character val = values.get(pathCondition);
		 if (val.equals('U'))
		 values.put(pathCondition, 'U');
		 else if (val.equals('T'))
		 values.put(pathCondition, 'T');
		 else if (val.equals('F'))
		 values.put(pathCondition, 'F');
		} else if (V13 <= 0 && V4 + V14 < V4 && 30 + V1 + V2 + 2 * V3 + 16 >= 30 + V7 + V8 + 2 * V9 + 16){
		 values.put(pathCondition, 'T');
		} else {
		 Character val = values.get(pathCondition);
		 if (val.equals('F') || val.equals('U'))
		 values.put(pathCondition, 'F');
		 else
		 values.put(pathCondition, 'T');
		}
 }


 private void getMinimumSizeFigObjectFlowState_1504945488_31(Integer V7, Integer V8, Integer V9, Integer V10, Integer V12, Integer V11, Integer V16, Integer V15) {

		String pathCondition = "getMinimumSizeFigObjectFlowState_1504945488_31";
		if(V7 == null || V8 == null || V9 == null || V10 == null || V12 == null || V11 == null || V16 == null || V15 == null){
		 Character val = values.get(pathCondition);
		 if (val.equals('U'))
		 values.put(pathCondition, 'U');
		 else if (val.equals('T'))
		 values.put(pathCondition, 'T');
		 else if (val.equals('F'))
		 values.put(pathCondition, 'F');
		} else if (V15 <= 0 && V10 + V16 >= V10 && 16 >= 30 + V7 + V8 + 2 * V9 + 16 && 16 + V10 + V16 + V11 + V12 + 2 * V9 + 8 >= 25){
		 values.put(pathCondition, 'T');
		} else {
		 Character val = values.get(pathCondition);
		 if (val.equals('F') || val.equals('U'))
		 values.put(pathCondition, 'F');
		 else
		 values.put(pathCondition, 'T');
		}
 }


 private void getMinimumSizeFigObjectFlowState_1504945488_46(Integer V7, Integer V8, Integer V9, Integer V16, Integer V15, Integer V1, Integer V2, Integer V3, Integer V4) {

		String pathCondition = "getMinimumSizeFigObjectFlowState_1504945488_46";
		if(V7 == null || V8 == null || V9 == null || V16 == null || V15 == null || V1 == null || V2 == null || V3 == null || V4 == null){
		 Character val = values.get(pathCondition);
		 if (val.equals('U'))
		 values.put(pathCondition, 'U');
		 else if (val.equals('T'))
		 values.put(pathCondition, 'T');
		 else if (val.equals('F'))
		 values.put(pathCondition, 'F');
		} else if (V15 <= 0 && V4 + V16 >= V4 && 30 + V1 + V2 + 2 * V3 + 16 < 30 + V7 + V8 + 2 * V9 + 16){
		 values.put(pathCondition, 'T');
		} else {
		 Character val = values.get(pathCondition);
		 if (val.equals('F') || val.equals('U'))
		 values.put(pathCondition, 'F');
		 else
		 values.put(pathCondition, 'T');
		}
 }


 private void getMinimumSizeFigObjectFlowState_1504945488_58(Integer V6, Integer V7, Integer V8, Integer V9, Integer V10, Integer V12, Integer V11, Integer V1, Integer V2, Integer V3, Integer V4, Integer V5) {

		String pathCondition = "getMinimumSizeFigObjectFlowState_1504945488_58";
		if(V6 == null || V7 == null || V8 == null || V9 == null || V10 == null || V12 == null || V11 == null || V1 == null || V2 == null || V3 == null || V4 == null || V5 == null){
		 Character val = values.get(pathCondition);
		 if (val.equals('U'))
		 values.put(pathCondition, 'U');
		 else if (val.equals('T'))
		 values.put(pathCondition, 'T');
		 else if (val.equals('F'))
		 values.put(pathCondition, 'F');
		} else if (30 + V1 + V2 + 2 * V3 + 16 >= 30 + V7 + V8 + 2 * V9 + 16 && 30 + V1 + V2 + 2 * V3 + 16 < 35 && V4 + V5 + V6 + 2 * V3 + 8 + 8 + V10 + V11 + V12 + 2 * V9 + 8 < 25){
		 values.put(pathCondition, 'T');
		} else {
		 Character val = values.get(pathCondition);
		 if (val.equals('F') || val.equals('U'))
		 values.put(pathCondition, 'F');
		 else
		 values.put(pathCondition, 'T');
		}
 }


 private void getMinimumSizeFigObjectFlowState_1504945488_12(Integer V14, Integer V13, Integer V1, Integer V2, Integer V3, Integer V4) {

		String pathCondition = "getMinimumSizeFigObjectFlowState_1504945488_12";
		if(V14 == null || V13 == null || V1 == null || V2 == null || V3 == null || V4 == null){
		 Character val = values.get(pathCondition);
		 if (val.equals('U'))
		 values.put(pathCondition, 'U');
		 else if (val.equals('T'))
		 values.put(pathCondition, 'T');
		 else if (val.equals('F'))
		 values.put(pathCondition, 'F');
		} else if (V13 <= 0 && V4 + V14 >= V4 && 30 + V1 + V2 + 2 * V3 + 16 >= 16 && 30 + V1 + V2 + 2 * V3 + 16 < 35){
		 values.put(pathCondition, 'T');
		} else {
		 Character val = values.get(pathCondition);
		 if (val.equals('F') || val.equals('U'))
		 values.put(pathCondition, 'F');
		 else
		 values.put(pathCondition, 'T');
		}
 }


 private void getMinimumSizeFigObjectFlowState_1504945488_34(Integer V7, Integer V8, Integer V9, Integer V10, Integer V12, Integer V11, Integer V16, Integer V15) {

		String pathCondition = "getMinimumSizeFigObjectFlowState_1504945488_34";
		if(V7 == null || V8 == null || V9 == null || V10 == null || V12 == null || V11 == null || V16 == null || V15 == null){
		 Character val = values.get(pathCondition);
		 if (val.equals('U'))
		 values.put(pathCondition, 'U');
		 else if (val.equals('T'))
		 values.put(pathCondition, 'T');
		 else if (val.equals('F'))
		 values.put(pathCondition, 'F');
		} else if (V15 <= 0 && V10 + V16 < V10 && 16 >= 30 + V7 + V8 + 2 * V9 + 16 && 16 + V10 + V11 + V12 + 2 * V9 + 8 >= 25){
		 values.put(pathCondition, 'T');
		} else {
		 Character val = values.get(pathCondition);
		 if (val.equals('F') || val.equals('U'))
		 values.put(pathCondition, 'F');
		 else
		 values.put(pathCondition, 'T');
		}
 }


 private void getMinimumSizeFigObjectFlowState_1504945488_35(Integer V7, Integer V8, Integer V9, Integer V10, Integer V12, Integer V11, Integer V16, Integer V15) {

		String pathCondition = "getMinimumSizeFigObjectFlowState_1504945488_35";
		if(V7 == null || V8 == null || V9 == null || V10 == null || V12 == null || V11 == null || V16 == null || V15 == null){
		 Character val = values.get(pathCondition);
		 if (val.equals('U'))
		 values.put(pathCondition, 'U');
		 else if (val.equals('T'))
		 values.put(pathCondition, 'T');
		 else if (val.equals('F'))
		 values.put(pathCondition, 'F');
		} else if (V15 <= 0 && V10 + V16 < V10 && 16 >= 30 + V7 + V8 + 2 * V9 + 16 && 16 + V10 + V11 + V12 + 2 * V9 + 8 < 25){
		 values.put(pathCondition, 'T');
		} else {
		 Character val = values.get(pathCondition);
		 if (val.equals('F') || val.equals('U'))
		 values.put(pathCondition, 'F');
		 else
		 values.put(pathCondition, 'T');
		}
 }


 private void getMinimumSizeFigObjectFlowState_1504945488_38(Integer V7, Integer V8, Integer V9, Integer V10, Integer V12, Integer V11) {

		String pathCondition = "getMinimumSizeFigObjectFlowState_1504945488_38";
		if(V7 == null || V8 == null || V9 == null || V10 == null || V12 == null || V11 == null){
		 Character val = values.get(pathCondition);
		 if (val.equals('U'))
		 values.put(pathCondition, 'U');
		 else if (val.equals('T'))
		 values.put(pathCondition, 'T');
		 else if (val.equals('F'))
		 values.put(pathCondition, 'F');
		} else if (16 >= 30 + V7 + V8 + 2 * V9 + 16 && 16 + V10 + V11 + V12 + 2 * V9 + 8 < 25){
		 values.put(pathCondition, 'T');
		} else {
		 Character val = values.get(pathCondition);
		 if (val.equals('F') || val.equals('U'))
		 values.put(pathCondition, 'F');
		 else
		 values.put(pathCondition, 'T');
		}
 }


 private void getMinimumSizeFigObjectFlowState_1504945488_71(Integer V6, Integer V1, Integer V2, Integer V3, Integer V4, Integer V5) {

		String pathCondition = "getMinimumSizeFigObjectFlowState_1504945488_71";
		if(V6 == null || V1 == null || V2 == null || V3 == null || V4 == null || V5 == null){
		 Character val = values.get(pathCondition);
		 if (val.equals('U'))
		 values.put(pathCondition, 'U');
		 else if (val.equals('T'))
		 values.put(pathCondition, 'T');
		 else if (val.equals('F'))
		 values.put(pathCondition, 'F');
		} else if (30 + V1 + V2 + 2 * V3 + 16 >= 35 && V4 + V5 + V6 + 2 * V3 + 8 + 8 + V4 + V5 + V6 + 2 * V3 + 8 >= 25){
		 values.put(pathCondition, 'T');
		} else {
		 Character val = values.get(pathCondition);
		 if (val.equals('F') || val.equals('U'))
		 values.put(pathCondition, 'F');
		 else
		 values.put(pathCondition, 'T');
		}
 }


 private void getMinimumSizeFigObjectFlowState_1504945488_11(Integer V14, Integer V13, Integer V1, Integer V2, Integer V3, Integer V4) {

		String pathCondition = "getMinimumSizeFigObjectFlowState_1504945488_11";
		if(V14 == null || V13 == null || V1 == null || V2 == null || V3 == null || V4 == null){
		 Character val = values.get(pathCondition);
		 if (val.equals('U'))
		 values.put(pathCondition, 'U');
		 else if (val.equals('T'))
		 values.put(pathCondition, 'T');
		 else if (val.equals('F'))
		 values.put(pathCondition, 'F');
		} else if (V13 <= 0 && V4 + V14 >= V4 && 30 + V1 + V2 + 2 * V3 + 16 >= 16 && 30 + V1 + V2 + 2 * V3 + 16 >= 35){
		 values.put(pathCondition, 'T');
		} else {
		 Character val = values.get(pathCondition);
		 if (val.equals('F') || val.equals('U'))
		 values.put(pathCondition, 'F');
		 else
		 values.put(pathCondition, 'T');
		}
 }


 private void getMinimumSizeFigObjectFlowState_1504945488_41(Integer V7, Integer V8, Integer V9, Integer V10, Integer V16, Integer V15, Integer V1, Integer V2, Integer V3) {

		String pathCondition = "getMinimumSizeFigObjectFlowState_1504945488_41";
		if(V7 == null || V8 == null || V9 == null || V10 == null || V16 == null || V15 == null || V1 == null || V2 == null || V3 == null){
		 Character val = values.get(pathCondition);
		 if (val.equals('U'))
		 values.put(pathCondition, 'U');
		 else if (val.equals('T'))
		 values.put(pathCondition, 'T');
		 else if (val.equals('F'))
		 values.put(pathCondition, 'F');
		} else if (V15 <= 0 && V10 + V16 >= V10 && 30 + V1 + V2 + 2 * V3 + 16 >= 30 + V7 + V8 + 2 * V9 + 16){
		 values.put(pathCondition, 'T');
		} else {
		 Character val = values.get(pathCondition);
		 if (val.equals('F') || val.equals('U'))
		 values.put(pathCondition, 'F');
		 else
		 values.put(pathCondition, 'T');
		}
 }


 private void getMinimumSizeFigObjectFlowState_1504945488_51(Integer V6, Integer V1, Integer V2, Integer V3, Integer V4, Integer V5) {

		String pathCondition = "getMinimumSizeFigObjectFlowState_1504945488_51";
		if(V6 == null || V1 == null || V2 == null || V3 == null || V4 == null || V5 == null){
		 Character val = values.get(pathCondition);
		 if (val.equals('U'))
		 values.put(pathCondition, 'U');
		 else if (val.equals('T'))
		 values.put(pathCondition, 'T');
		 else if (val.equals('F'))
		 values.put(pathCondition, 'F');
		} else if (30 + V1 + V2 + 2 * V3 + 16 >= 16 && 30 + V1 + V2 + 2 * V3 + 16 < 35 && V4 + V5 + V6 + 2 * V3 + 8 + 8 + 8 >= 25){
		 values.put(pathCondition, 'T');
		} else {
		 Character val = values.get(pathCondition);
		 if (val.equals('F') || val.equals('U'))
		 values.put(pathCondition, 'F');
		 else
		 values.put(pathCondition, 'T');
		}
 }


 private void getMinimumSizeFigObjectFlowState_1504945488_55(Integer V6, Integer V7, Integer V8, Integer V9, Integer V10, Integer V12, Integer V11, Integer V1, Integer V2, Integer V3, Integer V4, Integer V5) {

		String pathCondition = "getMinimumSizeFigObjectFlowState_1504945488_55";
		if(V6 == null || V7 == null || V8 == null || V9 == null || V10 == null || V12 == null || V11 == null || V1 == null || V2 == null || V3 == null || V4 == null || V5 == null){
		 Character val = values.get(pathCondition);
		 if (val.equals('U'))
		 values.put(pathCondition, 'U');
		 else if (val.equals('T'))
		 values.put(pathCondition, 'T');
		 else if (val.equals('F'))
		 values.put(pathCondition, 'F');
		} else if (30 + V1 + V2 + 2 * V3 + 16 >= 30 + V7 + V8 + 2 * V9 + 16 && 30 + V1 + V2 + 2 * V3 + 16 >= 35 && V4 + V5 + V6 + 2 * V3 + 8 + 8 + V10 + V11 + V12 + 2 * V9 + 8 >= 25){
		 values.put(pathCondition, 'T');
		} else {
		 Character val = values.get(pathCondition);
		 if (val.equals('F') || val.equals('U'))
		 values.put(pathCondition, 'F');
		 else
		 values.put(pathCondition, 'T');
		}
 }


 private void getMinimumSizeFigObjectFlowState_1504945488_23(Integer V6, Integer V14, Integer V13, Integer V1, Integer V2, Integer V3, Integer V4, Integer V5) {

		String pathCondition = "getMinimumSizeFigObjectFlowState_1504945488_23";
		if(V6 == null || V14 == null || V13 == null || V1 == null || V2 == null || V3 == null || V4 == null || V5 == null){
		 Character val = values.get(pathCondition);
		 if (val.equals('U'))
		 values.put(pathCondition, 'U');
		 else if (val.equals('T'))
		 values.put(pathCondition, 'T');
		 else if (val.equals('F'))
		 values.put(pathCondition, 'F');
		} else if (V13 <= 0 && V4 + V14 < V4 && 30 + V1 + V2 + 2 * V3 + 16 < 16 && V4 + V5 + V6 + 2 * V3 + 8 + 8 + 8 < 25){
		 values.put(pathCondition, 'T');
		} else {
		 Character val = values.get(pathCondition);
		 if (val.equals('F') || val.equals('U'))
		 values.put(pathCondition, 'F');
		 else
		 values.put(pathCondition, 'T');
		}
 }


 private void getMinimumSizeFigObjectFlowState_1504945488_20(Integer V14, Integer V13, Integer V1, Integer V2, Integer V3, Integer V4) {

		String pathCondition = "getMinimumSizeFigObjectFlowState_1504945488_20";
		if(V14 == null || V13 == null || V1 == null || V2 == null || V3 == null || V4 == null){
		 Character val = values.get(pathCondition);
		 if (val.equals('U'))
		 values.put(pathCondition, 'U');
		 else if (val.equals('T'))
		 values.put(pathCondition, 'T');
		 else if (val.equals('F'))
		 values.put(pathCondition, 'F');
		} else if (V13 <= 0 && V4 + V14 < V4 && 30 + V1 + V2 + 2 * V3 + 16 >= 16 && 30 + V1 + V2 + 2 * V3 + 16 >= 35){
		 values.put(pathCondition, 'T');
		} else {
		 Character val = values.get(pathCondition);
		 if (val.equals('F') || val.equals('U'))
		 values.put(pathCondition, 'F');
		 else
		 values.put(pathCondition, 'T');
		}
 }


 private void getMinimumSizeFigObjectFlowState_1504945488_64(Integer V6, Integer V7, Integer V8, Integer V9, Integer V12, Integer V11, Integer V1, Integer V2, Integer V3, Integer V4, Integer V5) {

		String pathCondition = "getMinimumSizeFigObjectFlowState_1504945488_64";
		if(V6 == null || V7 == null || V8 == null || V9 == null || V12 == null || V11 == null || V1 == null || V2 == null || V3 == null || V4 == null || V5 == null){
		 Character val = values.get(pathCondition);
		 if (val.equals('U'))
		 values.put(pathCondition, 'U');
		 else if (val.equals('T'))
		 values.put(pathCondition, 'T');
		 else if (val.equals('F'))
		 values.put(pathCondition, 'F');
		} else if (30 + V1 + V2 + 2 * V3 + 16 >= 30 + V7 + V8 + 2 * V9 + 16 && 30 + V1 + V2 + 2 * V3 + 16 >= 35 && V4 + V5 + V6 + 2 * V3 + 8 + 8 + V4 + V11 + V12 + 2 * V9 + 8 < 25){
		 values.put(pathCondition, 'T');
		} else {
		 Character val = values.get(pathCondition);
		 if (val.equals('F') || val.equals('U'))
		 values.put(pathCondition, 'F');
		 else
		 values.put(pathCondition, 'T');
		}
 }


 private void getMinimumSizeFigObjectFlowState_1504945488_42(Integer V7, Integer V8, Integer V9, Integer V10, Integer V16, Integer V15, Integer V1, Integer V2, Integer V3) {

		String pathCondition = "getMinimumSizeFigObjectFlowState_1504945488_42";
		if(V7 == null || V8 == null || V9 == null || V10 == null || V16 == null || V15 == null || V1 == null || V2 == null || V3 == null){
		 Character val = values.get(pathCondition);
		 if (val.equals('U'))
		 values.put(pathCondition, 'U');
		 else if (val.equals('T'))
		 values.put(pathCondition, 'T');
		 else if (val.equals('F'))
		 values.put(pathCondition, 'F');
		} else if (V15 <= 0 && V10 + V16 >= V10 && 30 + V1 + V2 + 2 * V3 + 16 < 30 + V7 + V8 + 2 * V9 + 16){
		 values.put(pathCondition, 'T');
		} else {
		 Character val = values.get(pathCondition);
		 if (val.equals('F') || val.equals('U'))
		 values.put(pathCondition, 'F');
		 else
		 values.put(pathCondition, 'T');
		}
 }


 private void getMinimumSizeFigObjectFlowState_1504945488_63(Integer V6, Integer V7, Integer V8, Integer V9, Integer V12, Integer V11, Integer V1, Integer V2, Integer V3, Integer V4, Integer V5) {

		String pathCondition = "getMinimumSizeFigObjectFlowState_1504945488_63";
		if(V6 == null || V7 == null || V8 == null || V9 == null || V12 == null || V11 == null || V1 == null || V2 == null || V3 == null || V4 == null || V5 == null){
		 Character val = values.get(pathCondition);
		 if (val.equals('U'))
		 values.put(pathCondition, 'U');
		 else if (val.equals('T'))
		 values.put(pathCondition, 'T');
		 else if (val.equals('F'))
		 values.put(pathCondition, 'F');
		} else if (30 + V1 + V2 + 2 * V3 + 16 >= 30 + V7 + V8 + 2 * V9 + 16 && 30 + V1 + V2 + 2 * V3 + 16 >= 35 && V4 + V5 + V6 + 2 * V3 + 8 + 8 + V4 + V11 + V12 + 2 * V9 + 8 >= 25){
		 values.put(pathCondition, 'T');
		} else {
		 Character val = values.get(pathCondition);
		 if (val.equals('F') || val.equals('U'))
		 values.put(pathCondition, 'F');
		 else
		 values.put(pathCondition, 'T');
		}
 }


 private void getMinimumSizeFigObjectFlowState_1504945488_44(Integer V7, Integer V8, Integer V9, Integer V10, Integer V16, Integer V15, Integer V1, Integer V2, Integer V3) {

		String pathCondition = "getMinimumSizeFigObjectFlowState_1504945488_44";
		if(V7 == null || V8 == null || V9 == null || V10 == null || V16 == null || V15 == null || V1 == null || V2 == null || V3 == null){
		 Character val = values.get(pathCondition);
		 if (val.equals('U'))
		 values.put(pathCondition, 'U');
		 else if (val.equals('T'))
		 values.put(pathCondition, 'T');
		 else if (val.equals('F'))
		 values.put(pathCondition, 'F');
		} else if (V15 <= 0 && V10 + V16 < V10 && 30 + V1 + V2 + 2 * V3 + 16 < 30 + V7 + V8 + 2 * V9 + 16){
		 values.put(pathCondition, 'T');
		} else {
		 Character val = values.get(pathCondition);
		 if (val.equals('F') || val.equals('U'))
		 values.put(pathCondition, 'F');
		 else
		 values.put(pathCondition, 'T');
		}
 }


 private void getMinimumSizeFigObjectFlowState_1504945488_9(Integer V14, Integer V13, Integer V15, Integer V4) {

		String pathCondition = "getMinimumSizeFigObjectFlowState_1504945488_9";
		if(V14 == null || V13 == null || V15 == null || V4 == null){
		 Character val = values.get(pathCondition);
		 if (val.equals('U'))
		 values.put(pathCondition, 'U');
		 else if (val.equals('T'))
		 values.put(pathCondition, 'T');
		 else if (val.equals('F'))
		 values.put(pathCondition, 'F');
		} else if (V13 <= 0 && V4 + V14 >= V4 && V15 > 0){
		 values.put(pathCondition, 'T');
		} else {
		 Character val = values.get(pathCondition);
		 if (val.equals('F') || val.equals('U'))
		 values.put(pathCondition, 'F');
		 else
		 values.put(pathCondition, 'T');
		}
 }


 private void getMinimumSizeFigObjectFlowState_1504945488_17(Integer V14, Integer V13, Integer V4) {

		String pathCondition = "getMinimumSizeFigObjectFlowState_1504945488_17";
		if(V14 == null || V13 == null || V4 == null){
		 Character val = values.get(pathCondition);
		 if (val.equals('U'))
		 values.put(pathCondition, 'U');
		 else if (val.equals('T'))
		 values.put(pathCondition, 'T');
		 else if (val.equals('F'))
		 values.put(pathCondition, 'F');
		} else if (V13 <= 0 && V4 + V14 < V4){
		 values.put(pathCondition, 'T');
		} else {
		 Character val = values.get(pathCondition);
		 if (val.equals('F') || val.equals('U'))
		 values.put(pathCondition, 'F');
		 else
		 values.put(pathCondition, 'T');
		}
 }


 private void getMinimumSizeFigObjectFlowState_1504945488_7(Integer V13) {

		String pathCondition = "getMinimumSizeFigObjectFlowState_1504945488_7";
		if(V13 == null){
		 Character val = values.get(pathCondition);
		 if (val.equals('U'))
		 values.put(pathCondition, 'U');
		 else if (val.equals('T'))
		 values.put(pathCondition, 'T');
		 else if (val.equals('F'))
		 values.put(pathCondition, 'F');
		} else if (V13 > 0){
		 values.put(pathCondition, 'T');
		} else {
		 Character val = values.get(pathCondition);
		 if (val.equals('F') || val.equals('U'))
		 values.put(pathCondition, 'F');
		 else
		 values.put(pathCondition, 'T');
		}
 }


 private void getMinimumSizeFigObjectFlowState_1504945488_27(Integer V15) {

		String pathCondition = "getMinimumSizeFigObjectFlowState_1504945488_27";
		if(V15 == null){
		 Character val = values.get(pathCondition);
		 if (val.equals('U'))
		 values.put(pathCondition, 'U');
		 else if (val.equals('T'))
		 values.put(pathCondition, 'T');
		 else if (val.equals('F'))
		 values.put(pathCondition, 'F');
		} else if (V15 >= 0 && V15 <= 0){
		 values.put(pathCondition, 'T');
		} else {
		 Character val = values.get(pathCondition);
		 if (val.equals('F') || val.equals('U'))
		 values.put(pathCondition, 'F');
		 else
		 values.put(pathCondition, 'T');
		}
 }


 private void getMinimumSizeFigObjectFlowState_1504945488_29(Integer V20, Integer V15) {

		String pathCondition = "getMinimumSizeFigObjectFlowState_1504945488_29";
		if(V20 == null || V15 == null){
		 Character val = values.get(pathCondition);
		 if (val.equals('U'))
		 values.put(pathCondition, 'U');
		 else if (val.equals('T'))
		 values.put(pathCondition, 'T');
		 else if (val.equals('F'))
		 values.put(pathCondition, 'F');
		} else if (V15 > 0 && V20 >= 0){
		 values.put(pathCondition, 'T');
		} else {
		 Character val = values.get(pathCondition);
		 if (val.equals('F') || val.equals('U'))
		 values.put(pathCondition, 'F');
		 else
		 values.put(pathCondition, 'T');
		}
 }


 private void getMinimumSizeFigObjectFlowState_1504945488_19(Integer V14, Integer V13, Integer V15, Integer V4) {

		String pathCondition = "getMinimumSizeFigObjectFlowState_1504945488_19";
		if(V14 == null || V13 == null || V15 == null || V4 == null){
		 Character val = values.get(pathCondition);
		 if (val.equals('U'))
		 values.put(pathCondition, 'U');
		 else if (val.equals('T'))
		 values.put(pathCondition, 'T');
		 else if (val.equals('F'))
		 values.put(pathCondition, 'F');
		} else if (V13 <= 0 && V4 + V14 < V4 && V15 <= 0){
		 values.put(pathCondition, 'T');
		} else {
		 Character val = values.get(pathCondition);
		 if (val.equals('F') || val.equals('U'))
		 values.put(pathCondition, 'F');
		 else
		 values.put(pathCondition, 'T');
		}
 }


 private void getMinimumSizeFigObjectFlowState_1504945488_66(Integer V6, Integer V7, Integer V8, Integer V9, Integer V12, Integer V11, Integer V1, Integer V2, Integer V3, Integer V4, Integer V5) {

		String pathCondition = "getMinimumSizeFigObjectFlowState_1504945488_66";
		if(V6 == null || V7 == null || V8 == null || V9 == null || V12 == null || V11 == null || V1 == null || V2 == null || V3 == null || V4 == null || V5 == null){
		 Character val = values.get(pathCondition);
		 if (val.equals('U'))
		 values.put(pathCondition, 'U');
		 else if (val.equals('T'))
		 values.put(pathCondition, 'T');
		 else if (val.equals('F'))
		 values.put(pathCondition, 'F');
		} else if (30 + V1 + V2 + 2 * V3 + 16 >= 30 + V7 + V8 + 2 * V9 + 16 && 30 + V1 + V2 + 2 * V3 + 16 < 35 && V4 + V5 + V6 + 2 * V3 + 8 + 8 + V4 + V11 + V12 + 2 * V9 + 8 < 25){
		 values.put(pathCondition, 'T');
		} else {
		 Character val = values.get(pathCondition);
		 if (val.equals('F') || val.equals('U'))
		 values.put(pathCondition, 'F');
		 else
		 values.put(pathCondition, 'T');
		}
 }


 private void getMinimumSizeFigObjectFlowState_1504945488_50(Integer V6, Integer V1, Integer V2, Integer V3, Integer V4, Integer V5) {

		String pathCondition = "getMinimumSizeFigObjectFlowState_1504945488_50";
		if(V6 == null || V1 == null || V2 == null || V3 == null || V4 == null || V5 == null){
		 Character val = values.get(pathCondition);
		 if (val.equals('U'))
		 values.put(pathCondition, 'U');
		 else if (val.equals('T'))
		 values.put(pathCondition, 'T');
		 else if (val.equals('F'))
		 values.put(pathCondition, 'F');
		} else if (30 + V1 + V2 + 2 * V3 + 16 >= 16 && 30 + V1 + V2 + 2 * V3 + 16 >= 35 && V4 + V5 + V6 + 2 * V3 + 8 + 8 + 8 < 25){
		 values.put(pathCondition, 'T');
		} else {
		 Character val = values.get(pathCondition);
		 if (val.equals('F') || val.equals('U'))
		 values.put(pathCondition, 'F');
		 else
		 values.put(pathCondition, 'T');
		}
 }


 private void getMinimumSizeFigObjectFlowState_1504945488_39(Integer V7, Integer V8, Integer V9, Integer V10, Integer V12, Integer V11) {

		String pathCondition = "getMinimumSizeFigObjectFlowState_1504945488_39";
		if(V7 == null || V8 == null || V9 == null || V10 == null || V12 == null || V11 == null){
		 Character val = values.get(pathCondition);
		 if (val.equals('U'))
		 values.put(pathCondition, 'U');
		 else if (val.equals('T'))
		 values.put(pathCondition, 'T');
		 else if (val.equals('F'))
		 values.put(pathCondition, 'F');
		} else if (16 < 30 + V7 + V8 + 2 * V9 + 16 && 16 + V10 + V11 + V12 + 2 * V9 + 8 >= 25){
		 values.put(pathCondition, 'T');
		} else {
		 Character val = values.get(pathCondition);
		 if (val.equals('F') || val.equals('U'))
		 values.put(pathCondition, 'F');
		 else
		 values.put(pathCondition, 'T');
		}
 }

}
