package runtime.evaluators.autogenerated;

import java.lang.ref.WeakReference;
import java.util.List;

import runtime.evaluators.AtLeastOneConditionEvaluator;

import java.util.Iterator;
public class UMLActivityDiagram_498153440 extends AtLeastOneConditionEvaluator {
	private Object currentObject;
	private String clsName;

	public UMLActivityDiagram_498153440(String clsName) {
		this.clsName = clsName;
	}

	public void monitor() throws ClassNotFoundException, NumberFormatException {

		currentObject = null;
		//currentObject =	 Class.forName(clsName).cast(currentObject); 
		currentObject = Class.forName(clsName, false,Thread.currentThread().getContextClassLoader()).cast(currentObject); 
 		if ( map.containsKey(clsName)) {
 			List<WeakReference<Object>> objectsList =	 map.get(clsName);
 			for (Iterator<WeakReference<Object>> it = objectsList.iterator();it.hasNext();) {
 				WeakReference<Object> object = it.next();
 				if (object.isEnqueued())
 					addQueuedObject(clsName, object);
 				else {
 					currentObject = object.get();
 					sfh.setCurrentStaticObject(currentObject);
 					fh.setCurrentObject(currentObject);

						String sV2 = expression("[org.argouml.i18n.Translator.bundles.table.length","int");
						Integer V2 = !sV2.isEmpty() ? Integer.parseInt(sV2) : null;
						String sV1 = expression("[org.argouml.i18n.Translator.initialized","boolean");
						Integer V1 = !sV1.isEmpty() ? parseBoolean(sV1) : null;

						getActionTransitionUMLActivityDiagram_498153440_18(V1, V2);
						getActionTransitionUMLActivityDiagram_498153440_16(V1, V2);
						getActionTransitionUMLActivityDiagram_498153440_22(V1, V2);
						getActionTransitionUMLActivityDiagram_498153440_0(V1);
						getActionTransitionUMLActivityDiagram_498153440_35(V1, V2);
				} 
			}
		}
	}

 private void getActionTransitionUMLActivityDiagram_498153440_18(Integer V1, Integer V2) {

		String pathCondition = "getActionTransitionUMLActivityDiagram_498153440_18";
		if(V1 == null || V2 == null){
		 Character val = values.get(pathCondition);
		 if (val.equals('U'))
		 values.put(pathCondition, 'U');
		 else if (val.equals('T'))
		 values.put(pathCondition, 'T');
		 else if (val.equals('F'))
		 values.put(pathCondition, 'F');
		} else if (V1 != 0 && V2 >= 0 && (-1106513832 & V2 - 1) >= 0 && (-1106513832 & V2 - 1) < V2 && (-1106513832 & V2 - 1) + 2 < V2 && (-1106513832 & V2 - 1) + 2 >= 0 && (-1106513832 & V2 - 1) + 2 < V2 && (-1106513832 & V2 - 1) + 2 != (-1106513832 & V2 - 1) && (-1106513832 & V2 - 1) + 2 + 2 >= V2){
		 values.put(pathCondition, 'T');
		} else {
		 Character val = values.get(pathCondition);
		 if (val.equals('F') || val.equals('U'))
		 values.put(pathCondition, 'F');
		 else
		 values.put(pathCondition, 'T');
		}
 }


 private void getActionTransitionUMLActivityDiagram_498153440_16(Integer V1, Integer V2) {

		String pathCondition = "getActionTransitionUMLActivityDiagram_498153440_16";
		if(V1 == null || V2 == null){
		 Character val = values.get(pathCondition);
		 if (val.equals('U'))
		 values.put(pathCondition, 'U');
		 else if (val.equals('T'))
		 values.put(pathCondition, 'T');
		 else if (val.equals('F'))
		 values.put(pathCondition, 'F');
		} else if (V1 != 0 && V2 >= 0 && 769795890 % V2 >= 0 && 769795890 % V2 < V2){
		 values.put(pathCondition, 'T');
		} else {
		 Character val = values.get(pathCondition);
		 if (val.equals('F') || val.equals('U'))
		 values.put(pathCondition, 'F');
		 else
		 values.put(pathCondition, 'T');
		}
 }


 private void getActionTransitionUMLActivityDiagram_498153440_22(Integer V1, Integer V2) {

		String pathCondition = "getActionTransitionUMLActivityDiagram_498153440_22";
		if(V1 == null || V2 == null){
		 Character val = values.get(pathCondition);
		 if (val.equals('U'))
		 values.put(pathCondition, 'U');
		 else if (val.equals('T'))
		 values.put(pathCondition, 'T');
		 else if (val.equals('F'))
		 values.put(pathCondition, 'F');
		} else if (V1 != 0 && V2 >= 0 && (-1106513832 & V2 - 1) >= 0 && (-1106513832 & V2 - 1) < V2){
		 values.put(pathCondition, 'T');
		} else {
		 Character val = values.get(pathCondition);
		 if (val.equals('F') || val.equals('U'))
		 values.put(pathCondition, 'F');
		 else
		 values.put(pathCondition, 'T');
		}
 }


 private void getActionTransitionUMLActivityDiagram_498153440_0(Integer V1) {

		String pathCondition = "getActionTransitionUMLActivityDiagram_498153440_0";
		if(V1 == null){
		 Character val = values.get(pathCondition);
		 if (val.equals('U'))
		 values.put(pathCondition, 'U');
		 else if (val.equals('T'))
		 values.put(pathCondition, 'T');
		 else if (val.equals('F'))
		 values.put(pathCondition, 'F');
		} else if (V1 == 0){
		 values.put(pathCondition, 'T');
		} else {
		 Character val = values.get(pathCondition);
		 if (val.equals('F') || val.equals('U'))
		 values.put(pathCondition, 'F');
		 else
		 values.put(pathCondition, 'T');
		}
 }


 private void getActionTransitionUMLActivityDiagram_498153440_35(Integer V1, Integer V2) {

		String pathCondition = "getActionTransitionUMLActivityDiagram_498153440_35";
		if(V1 == null || V2 == null){
		 Character val = values.get(pathCondition);
		 if (val.equals('U'))
		 values.put(pathCondition, 'U');
		 else if (val.equals('T'))
		 values.put(pathCondition, 'T');
		 else if (val.equals('F'))
		 values.put(pathCondition, 'F');
		} else if (V1 != 0 && V2 >= 0 && (1871813854 & V2 - 1) >= 0 && (1871813854 & V2 - 1) < V2){
		 values.put(pathCondition, 'T');
		} else {
		 Character val = values.get(pathCondition);
		 if (val.equals('F') || val.equals('U'))
		 values.put(pathCondition, 'F');
		 else
		 values.put(pathCondition, 'T');
		}
 }

}
