package defs;

public class Defs {
	// Customize them.
	public static final String z3Path = "/usr/local/bin/z3";

	// Leave them alone.
	public static final String fragmentedHome = "./";
	public static final String conditionsHome = "../conditions";
	public static final String jbseHome = "../jbse/";
	public static final String targetClassPath = fragmentedHome + "bin/";
	public static final String jreClassPath = fragmentedHome + "data/jre/rt.jar";
	public static final String jbseClassPath = jbseHome + "bin/";
	public static final String targetSourcePath = fragmentedHome + "src/";
	public static final String jreSourcePath = fragmentedHome + "data/jre/src.zip";
	public static final String jbseSourcePath = jbseHome + "src/";
	public static final String testDataPath = fragmentedHome + "tst/testdata/";

	// Leave them alone, or add more stuff.
	public static final String[] classPath = { jbseClassPath, jreClassPath, targetClassPath, testDataPath };
	public static final String[] sourcePath = { jbseSourcePath, jreSourcePath};
	
	public static final String jbseOutput = fragmentedHome + "out/";
	public static final String fragmentedOutput = fragmentedHome + "fragmented/";
	public static final String serializedObjects = fragmentedHome + "serialized/";
	public static final String autogeneratedEvaluators = conditionsHome + "src/main/java/runtime/evaluators/autogenerated/";
	public static final String logs = "../logs/";
	
	public static final String EXCLUSIONS = "JavaExclusions.txt";
}
