package runtime.evaluators;

import java.util.concurrent.ConcurrentHashMap;

import fieldhelper.FieldHelper;
import fieldhelper.StaticFieldHelper;
import runtime.evaluators.autogenerated.*;

import java.util.HashMap;
import java.util.HashSet;
import java.lang.ref.WeakReference;
import java.util.List;
import java.util.Set;

public class AtLeastOneConditionEvaluator implements ConditionEvaluator{

	protected FieldHelper fh = new FieldHelper();
	protected StaticFieldHelper sfh = new StaticFieldHelper();

	protected static HashMap<String, Character> values = new HashMap<String, Character>();
	protected static ConcurrentHashMap<String,List<WeakReference<Object>>> map;

	protected HashMap<String, Set<WeakReference<Object>>> queuedObjects = new HashMap<>();


    	private void initValues1() {
			values.put("getMinimumSizeFigPool_1211542992_18",'U');
			values.put("setHandleBoxFigPartition$SelectionPartition_2107151569_5",'U');
			values.put("translateWithContentsFigPartition_24247365_24",'U');
			values.put("getActionStartPseudoStateUMLActivityDiagram_229454532_43",'U');
			values.put("initializeFigPool_17674300_1",'U');
			values.put("initializeFigPool_17674300_0",'U');
			values.put("initFigsFigPartition_1829964687_3",'U');
			values.put("initFigsFigPartition_1829964687_1",'U');
			values.put("initFigsFigPartition_1829964687_4",'U');
			values.put("updateStateTextFigObjectFlowState_657916191_109",'U');
			values.put("getActionObjectFlowStateUMLActivityDiagram_768016631_7",'U');
			values.put("getActionObjectFlowStateUMLActivityDiagram_768016631_22",'U');
			values.put("getActionSwimlaneUMLActivityDiagram_1620898305_165",'U');
			values.put("getActionSwimlaneUMLActivityDiagram_1620898305_0",'U');
			values.put("getActionSwimlaneUMLActivityDiagram_1620898305_60",'U');
			values.put("getActionSwimlaneUMLActivityDiagram_1620898305_83",'U');
			values.put("setStandardBoundsFigPartition_1367219204_13",'U');
			values.put("setStandardBoundsFigPartition_1367219204_10",'U');
			values.put("setStandardBoundsFigPartition_1367219204_15",'U');
			values.put("setStandardBoundsFigPartition_1367219204_17",'U');
			values.put("setStandardBoundsFigPartition_1367219204_5",'U');
			values.put("setEnclosingFigFigObjectFlowState_773984195_6",'U');
			values.put("setFilledFigPool_205142212_1",'U');
			values.put("getFigNodeForActivityDiagramRenderer_208944555_1",'U');
			values.put("getActionJunctionPseudoStateUMLActivityDiagram_1021587214_31",'U');
			values.put("getActionJunctionPseudoStateUMLActivityDiagram_1021587214_20",'U');
			values.put("getActionJunctionPseudoStateUMLActivityDiagram_1021587214_19",'U');
			values.put("getActionJunctionPseudoStateUMLActivityDiagram_1021587214_36",'U');
			values.put("setFilledFigActionState_1994787237_1",'U');
			values.put("getActionStateUMLActivityDiagram_390667516_7",'U');
			values.put("getActionStateUMLActivityDiagram_390667516_5",'U');
			values.put("getActionFinalPseudoStateUMLActivityDiagram_92249000_7",'U');
			values.put("getActionFinalPseudoStateUMLActivityDiagram_92249000_21",'U');
			values.put("getActionFinalPseudoStateUMLActivityDiagram_92249000_0",'U');
			values.put("getActionTransitionUMLActivityDiagram_498153440_18",'U');
			values.put("getActionTransitionUMLActivityDiagram_498153440_16",'U');
			values.put("getActionTransitionUMLActivityDiagram_498153440_22",'U');
			values.put("getActionTransitionUMLActivityDiagram_498153440_0",'U');
			values.put("getActionTransitionUMLActivityDiagram_498153440_35",'U');
			values.put("dragHandleFigPartition$SelectionPartition_832543441_6",'U');
			values.put("dragHandleFigPartition$SelectionPartition_832543441_13",'U');
			values.put("setPreviousPartitionFigPartition_2088707753_1",'U');
			values.put("setPreviousPartitionFigPartition_2088707753_3",'U');
			values.put("setStandardBoundsFigActionState_1860133333_19",'U');
			values.put("setStandardBoundsFigActionState_1860133333_20",'U');
			values.put("setStandardBoundsFigActionState_1860133333_18",'U');
			values.put("setFillColorFigPool_121457410_2",'U');
			values.put("setFillColorFigPool_121457410_1",'U');
			values.put("setFillColorFigPool_121457410_0",'U');
			values.put("setFillColorFigPool_121457410_4",'U');
			values.put("getMinimumSizeFigPartition_1481300586_16",'U');
			values.put("encloserChangedUMLActivityDiagram_1421929786_41",'U');
			values.put("encloserChangedUMLActivityDiagram_1421929786_38",'U');
			values.put("encloserChangedUMLActivityDiagram_1421929786_40",'U');
			values.put("encloserChangedUMLActivityDiagram_1421929786_2",'U');
			values.put("initFigsFigObjectFlowState_993089451_1",'U');
			values.put("paintFigPartition$SelectionPartition_194404586_1",'U');
			values.put("getActionJoinPseudoStateUMLActivityDiagram_2115832996_7",'U');
			values.put("getActionJoinPseudoStateUMLActivityDiagram_2115832996_40",'U');
			values.put("getActionJoinPseudoStateUMLActivityDiagram_2115832996_34",'U');
			values.put("getActionJoinPseudoStateUMLActivityDiagram_2115832996_22",'U');
			values.put("getActionJoinPseudoStateUMLActivityDiagram_2115832996_17",'U');
			values.put("getActionJoinPseudoStateUMLActivityDiagram_2115832996_33",'U');
			values.put("getActionJoinPseudoStateUMLActivityDiagram_2115832996_6",'U');
			values.put("getActionJoinPseudoStateUMLActivityDiagram_2115832996_19",'U');
			values.put("getActionJoinPseudoStateUMLActivityDiagram_2115832996_36",'U');
			values.put("getActionJoinPseudoStateUMLActivityDiagram_2115832996_5",'U');
			values.put("getActionJoinPseudoStateUMLActivityDiagram_2115832996_0",'U');
			values.put("getActionJoinPseudoStateUMLActivityDiagram_2115832996_21",'U');
			values.put("getRelocationCandidatesUMLActivityDiagram_1758469639_21",'U');
			values.put("getRelocationCandidatesUMLActivityDiagram_1758469639_22",'U');
			values.put("getRelocationCandidatesUMLActivityDiagram_1758469639_38",'U');
			values.put("getRelocationCandidatesUMLActivityDiagram_1758469639_39",'U');
			values.put("getRelocationCandidatesUMLActivityDiagram_1758469639_34",'U');
			values.put("getRelocationCandidatesUMLActivityDiagram_1758469639_47",'U');
			values.put("getRelocationCandidatesUMLActivityDiagram_1758469639_52",'U');
			values.put("getRelocationCandidatesUMLActivityDiagram_1758469639_36",'U');
			values.put("getRelocationCandidatesUMLActivityDiagram_1758469639_35",'U');
			values.put("getRelocationCandidatesUMLActivityDiagram_1758469639_43",'U');
			values.put("getRelocationCandidatesUMLActivityDiagram_1758469639_46",'U');
			values.put("getRelocationCandidatesUMLActivityDiagram_1758469639_45",'U');
			values.put("getRelocationCandidatesUMLActivityDiagram_1758469639_2",'U');
			values.put("getRelocationCandidatesUMLActivityDiagram_1758469639_6",'U');
			values.put("getRelocationCandidatesUMLActivityDiagram_1758469639_5",'U');
			values.put("getRelocationCandidatesUMLActivityDiagram_1758469639_24",'U');
			values.put("getRelocationCandidatesUMLActivityDiagram_1758469639_8",'U');
			values.put("getRelocationCandidatesUMLActivityDiagram_1758469639_26",'U');
			values.put("getRelocationCandidatesUMLActivityDiagram_1758469639_9",'U');
			values.put("getRelocationCandidatesUMLActivityDiagram_1758469639_31",'U');
			values.put("getRelocationCandidatesUMLActivityDiagram_1758469639_20",'U');
			values.put("getRelocationCandidatesUMLActivityDiagram_1758469639_27",'U');
			values.put("getRelocationCandidatesUMLActivityDiagram_1758469639_28",'U');
			values.put("getRelocationCandidatesUMLActivityDiagram_1758469639_29",'U');
			values.put("getDragDependenciesFigPartition_1617146438_7",'U');
			values.put("getDragDependenciesFigPartition_1617146438_9",'U');
			values.put("getDragDependenciesFigPartition_1617146438_6",'U');
			values.put("getDragDependenciesFigPartition_1617146438_5",'U');
			values.put("getActionSubactivityStateUMLActivityDiagram_1823949299_18",'U');
			values.put("getActionSubactivityStateUMLActivityDiagram_1823949299_41",'U');
			values.put("getActionSubactivityStateUMLActivityDiagram_1823949299_45",'U');
			values.put("getActionSubactivityStateUMLActivityDiagram_1823949299_38",'U');
			values.put("getActionSubactivityStateUMLActivityDiagram_1823949299_42",'U');
			values.put("getActionSubactivityStateUMLActivityDiagram_1823949299_17",'U');
			values.put("getActionSubactivityStateUMLActivityDiagram_1823949299_16",'U');
			values.put("getActionSubactivityStateUMLActivityDiagram_1823949299_20",'U');
			values.put("modelChangedFigObjectFlowState_1892591522_42",'U');
			values.put("modelChangedFigObjectFlowState_1892591522_43",'U');
			values.put("setFillColorFigPartition_1480666308_1",'U');
			values.put("setFillColorFigPartition_1480666308_5",'U');
			values.put("setFillColorFigPartition_1480666308_3",'U');
			values.put("hitHandleFigPartition$SelectionPartition_1410860176_1",'U');
			values.put("hitHandleFigPartition$SelectionPartition_1410860176_4",'U');
			values.put("hitHandleFigPartition$SelectionPartition_1410860176_3",'U');
			values.put("setLineColorFigPartition_800477427_1",'U');
			values.put("setLineColorFigPartition_800477427_5",'U');
			values.put("setLineColorFigPartition_800477427_3",'U');
			values.put("setFillColorFigActionState_1973580437_1",'U');
			values.put("setFillColorFigActionState_1973580437_0",'U');
			values.put("createBigPortFigFigPartition_1335031698_5",'U');
			values.put("createBigPortFigFigPartition_1335031698_2",'U');
			values.put("createBigPortFigFigPartition_1335031698_3",'U');
			values.put("changePartitionUMLActivityDiagram_634363631_0",'U');
			values.put("changePartitionUMLActivityDiagram_634363631_3",'U');
			values.put("changePartitionUMLActivityDiagram_634363631_1",'U');
			values.put("changePartitionUMLActivityDiagram_634363631_4",'U');
			values.put("setStandardBoundsFigObjectFlowState_1343574302_26",'U');
			values.put("setStandardBoundsFigObjectFlowState_1343574302_28",'U');
			values.put("getActionCallStateUMLActivityDiagram_187627194_36",'U');
			values.put("getActionCallStateUMLActivityDiagram_187627194_46",'U');
			values.put("getActionCallStateUMLActivityDiagram_187627194_7",'U');
			values.put("getActionCallStateUMLActivityDiagram_187627194_45",'U');
			values.put("getActionCallStateUMLActivityDiagram_187627194_43",'U');
			values.put("getActionCallStateUMLActivityDiagram_187627194_34",'U');
			values.put("getActionCallStateUMLActivityDiagram_187627194_41",'U');
			values.put("getActionCallStateUMLActivityDiagram_187627194_37",'U');
			values.put("getActionCallStateUMLActivityDiagram_187627194_33",'U');
			values.put("getActionCallStateUMLActivityDiagram_187627194_16",'U');
			values.put("getActionCallStateUMLActivityDiagram_187627194_6",'U');
			values.put("getActionCallStateUMLActivityDiagram_187627194_20",'U');
			values.put("getActionCallStateUMLActivityDiagram_187627194_40",'U');
			values.put("getActionCallStateUMLActivityDiagram_187627194_5",'U');
			values.put("getActionCallStateUMLActivityDiagram_187627194_18",'U');
			values.put("getActionCallStateUMLActivityDiagram_187627194_0",'U');
			values.put("getActionCallStateUMLActivityDiagram_187627194_21",'U');
			values.put("getActionCallStateUMLActivityDiagram_187627194_38",'U');
			values.put("getActionCallStateUMLActivityDiagram_187627194_47",'U');
			values.put("getMinimumSizeFigActionState_988386457_5",'U');
			values.put("getMinimumSizeFigActionState_988386457_35",'U');
			values.put("getMinimumSizeFigActionState_988386457_36",'U');
			values.put("getMinimumSizeFigActionState_988386457_6",'U');
			values.put("getMinimumSizeFigActionState_988386457_13",'U');
			values.put("getMinimumSizeFigActionState_988386457_17",'U');
			values.put("getMinimumSizeFigActionState_988386457_20",'U');
			values.put("getMinimumSizeFigActionState_988386457_14",'U');
			values.put("getMinimumSizeFigActionState_988386457_8",'U');
			values.put("getMinimumSizeFigActionState_988386457_34",'U');
			values.put("getMinimumSizeFigActionState_988386457_19",'U');
			values.put("getMinimumSizeFigActionState_988386457_4",'U');
			values.put("getMinimumSizeFigActionState_988386457_18",'U');
    	}

	protected void addQueuedObject(String clsName, WeakReference<Object> object) {
		Set<WeakReference<Object>> objectsSet = queuedObjects.get(clsName);
		if (objectsSet == null) {
			objectsSet = new HashSet<>();
			objectsSet.add(object);
			queuedObjects.put(clsName, objectsSet);
		} else if (!objectsSet.contains(object)) {
			objectsSet.add(object);
		}
	}

	@Override
	public void clearQueue() {
		queuedObjects.clear();
	}

	@Override
	public HashMap<String, Set<WeakReference<Object>>> getQueuedObjects() {
		return queuedObjects;
	}

	@Override
	public int sizeQueuedObjects() {
		return queuedObjects.size();
	}

	@Override
	public HashMap<String, Character> monitorValues(ConcurrentHashMap<String,List<WeakReference<Object>>> map) {

		AtLeastOneConditionEvaluator.map = map;
		initValues1();
		try { 
				getMinimumSizeFigPool_1211542992();
				setHandleBoxFigPartition$SelectionPartition_2107151569();
				translateWithContentsFigPartition_24247365();
				getActionStartPseudoStateUMLActivityDiagram_229454532();
				initializeFigPool_17674300();
				initFigsFigPartition_1829964687();
				updateStateTextFigObjectFlowState_657916191();
				getActionObjectFlowStateUMLActivityDiagram_768016631();
				getActionSwimlaneUMLActivityDiagram_1620898305();
				setStandardBoundsFigPartition_1367219204();
				setEnclosingFigFigObjectFlowState_773984195();
				setFilledFigPool_205142212();
				getFigNodeForActivityDiagramRenderer_208944555();
				getActionJunctionPseudoStateUMLActivityDiagram_1021587214();
				setFilledFigActionState_1994787237();
				getActionStateUMLActivityDiagram_390667516();
				getActionFinalPseudoStateUMLActivityDiagram_92249000();
				getActionTransitionUMLActivityDiagram_498153440();
				dragHandleFigPartition$SelectionPartition_832543441();
				setPreviousPartitionFigPartition_2088707753();
				setStandardBoundsFigActionState_1860133333();
				setFillColorFigPool_121457410();
				getMinimumSizeFigPartition_1481300586();
				encloserChangedUMLActivityDiagram_1421929786();
				initFigsFigObjectFlowState_993089451();
				paintFigPartition$SelectionPartition_194404586();
				getActionJoinPseudoStateUMLActivityDiagram_2115832996();
				getRelocationCandidatesUMLActivityDiagram_1758469639();
				getDragDependenciesFigPartition_1617146438();
				getActionSubactivityStateUMLActivityDiagram_1823949299();
				modelChangedFigObjectFlowState_1892591522();
				setFillColorFigPartition_1480666308();
				hitHandleFigPartition$SelectionPartition_1410860176();
				setLineColorFigPartition_800477427();
				setFillColorFigActionState_1973580437();
				createBigPortFigFigPartition_1335031698();
				changePartitionUMLActivityDiagram_634363631();
				setStandardBoundsFigObjectFlowState_1343574302();
				getActionCallStateUMLActivityDiagram_187627194();
				getMinimumSizeFigActionState_988386457();
		} catch (NumberFormatException e) {
			e.printStackTrace();
		} catch (ClassNotFoundException e) {
			e.printStackTrace();
		}
		return values;
	}
	
	private void getMinimumSizeFigPool_1211542992() throws ClassNotFoundException, NumberFormatException {
		FigPool_1211542992 m = new FigPool_1211542992("org.argouml.uml.diagram.activity.ui.FigPool");
		m.monitor();
	}
	private void setHandleBoxFigPartition$SelectionPartition_2107151569() throws ClassNotFoundException, NumberFormatException {
		FigPartition$SelectionPartition_2107151569 m = new FigPartition$SelectionPartition_2107151569("org.argouml.uml.diagram.activity.ui.FigPartition$SelectionPartition");
		m.monitor();
	}
	private void translateWithContentsFigPartition_24247365() throws ClassNotFoundException, NumberFormatException {
		FigPartition_24247365 m = new FigPartition_24247365("org.argouml.uml.diagram.activity.ui.FigPartition");
		m.monitor();
	}
	private void getActionStartPseudoStateUMLActivityDiagram_229454532() throws ClassNotFoundException, NumberFormatException {
		UMLActivityDiagram_229454532 m = new UMLActivityDiagram_229454532("org.argouml.uml.diagram.activity.ui.UMLActivityDiagram");
		m.monitor();
	}
	private void initializeFigPool_17674300() throws ClassNotFoundException, NumberFormatException {
		FigPool_17674300 m = new FigPool_17674300("org.argouml.uml.diagram.activity.ui.FigPool");
		m.monitor();
	}
	private void initFigsFigPartition_1829964687() throws ClassNotFoundException, NumberFormatException {
		FigPartition_1829964687 m = new FigPartition_1829964687("org.argouml.uml.diagram.activity.ui.FigPartition");
		m.monitor();
	}
	private void updateStateTextFigObjectFlowState_657916191() throws ClassNotFoundException, NumberFormatException {
		FigObjectFlowState_657916191 m = new FigObjectFlowState_657916191("org.argouml.uml.diagram.activity.ui.FigObjectFlowState");
		m.monitor();
	}
	private void getActionObjectFlowStateUMLActivityDiagram_768016631() throws ClassNotFoundException, NumberFormatException {
		UMLActivityDiagram_768016631 m = new UMLActivityDiagram_768016631("org.argouml.uml.diagram.activity.ui.UMLActivityDiagram");
		m.monitor();
	}
	private void getActionSwimlaneUMLActivityDiagram_1620898305() throws ClassNotFoundException, NumberFormatException {
		UMLActivityDiagram_1620898305 m = new UMLActivityDiagram_1620898305("org.argouml.uml.diagram.activity.ui.UMLActivityDiagram");
		m.monitor();
	}
	private void setStandardBoundsFigPartition_1367219204() throws ClassNotFoundException, NumberFormatException {
		FigPartition_1367219204 m = new FigPartition_1367219204("org.argouml.uml.diagram.activity.ui.FigPartition");
		m.monitor();
	}
	private void setEnclosingFigFigObjectFlowState_773984195() throws ClassNotFoundException, NumberFormatException {
		FigObjectFlowState_773984195 m = new FigObjectFlowState_773984195("org.argouml.uml.diagram.activity.ui.FigObjectFlowState");
		m.monitor();
	}
	private void setFilledFigPool_205142212() throws ClassNotFoundException, NumberFormatException {
		FigPool_205142212 m = new FigPool_205142212("org.argouml.uml.diagram.activity.ui.FigPool");
		m.monitor();
	}
	private void getFigNodeForActivityDiagramRenderer_208944555() throws ClassNotFoundException, NumberFormatException {
		ActivityDiagramRenderer_208944555 m = new ActivityDiagramRenderer_208944555("org.argouml.uml.diagram.activity.ui.ActivityDiagramRenderer");
		m.monitor();
	}
	private void getActionJunctionPseudoStateUMLActivityDiagram_1021587214() throws ClassNotFoundException, NumberFormatException {
		UMLActivityDiagram_1021587214 m = new UMLActivityDiagram_1021587214("org.argouml.uml.diagram.activity.ui.UMLActivityDiagram");
		m.monitor();
	}
	private void setFilledFigActionState_1994787237() throws ClassNotFoundException, NumberFormatException {
		FigActionState_1994787237 m = new FigActionState_1994787237("org.argouml.uml.diagram.activity.ui.FigActionState");
		m.monitor();
	}
	private void getActionStateUMLActivityDiagram_390667516() throws ClassNotFoundException, NumberFormatException {
		UMLActivityDiagram_390667516 m = new UMLActivityDiagram_390667516("org.argouml.uml.diagram.activity.ui.UMLActivityDiagram");
		m.monitor();
	}
	private void getActionFinalPseudoStateUMLActivityDiagram_92249000() throws ClassNotFoundException, NumberFormatException {
		UMLActivityDiagram_92249000 m = new UMLActivityDiagram_92249000("org.argouml.uml.diagram.activity.ui.UMLActivityDiagram");
		m.monitor();
	}
	private void getActionTransitionUMLActivityDiagram_498153440() throws ClassNotFoundException, NumberFormatException {
		UMLActivityDiagram_498153440 m = new UMLActivityDiagram_498153440("org.argouml.uml.diagram.activity.ui.UMLActivityDiagram");
		m.monitor();
	}
	private void dragHandleFigPartition$SelectionPartition_832543441() throws ClassNotFoundException, NumberFormatException {
		FigPartition$SelectionPartition_832543441 m = new FigPartition$SelectionPartition_832543441("org.argouml.uml.diagram.activity.ui.FigPartition$SelectionPartition");
		m.monitor();
	}
	private void setPreviousPartitionFigPartition_2088707753() throws ClassNotFoundException, NumberFormatException {
		FigPartition_2088707753 m = new FigPartition_2088707753("org.argouml.uml.diagram.activity.ui.FigPartition");
		m.monitor();
	}
	private void setStandardBoundsFigActionState_1860133333() throws ClassNotFoundException, NumberFormatException {
		FigActionState_1860133333 m = new FigActionState_1860133333("org.argouml.uml.diagram.activity.ui.FigActionState");
		m.monitor();
	}
	private void setFillColorFigPool_121457410() throws ClassNotFoundException, NumberFormatException {
		FigPool_121457410 m = new FigPool_121457410("org.argouml.uml.diagram.activity.ui.FigPool");
		m.monitor();
	}
	private void getMinimumSizeFigPartition_1481300586() throws ClassNotFoundException, NumberFormatException {
		FigPartition_1481300586 m = new FigPartition_1481300586("org.argouml.uml.diagram.activity.ui.FigPartition");
		m.monitor();
	}
	private void encloserChangedUMLActivityDiagram_1421929786() throws ClassNotFoundException, NumberFormatException {
		UMLActivityDiagram_1421929786 m = new UMLActivityDiagram_1421929786("org.argouml.uml.diagram.activity.ui.UMLActivityDiagram");
		m.monitor();
	}
	private void initFigsFigObjectFlowState_993089451() throws ClassNotFoundException, NumberFormatException {
		FigObjectFlowState_993089451 m = new FigObjectFlowState_993089451("org.argouml.uml.diagram.activity.ui.FigObjectFlowState");
		m.monitor();
	}
	private void paintFigPartition$SelectionPartition_194404586() throws ClassNotFoundException, NumberFormatException {
		FigPartition$SelectionPartition_194404586 m = new FigPartition$SelectionPartition_194404586("org.argouml.uml.diagram.activity.ui.FigPartition$SelectionPartition");
		m.monitor();
	}
	private void getActionJoinPseudoStateUMLActivityDiagram_2115832996() throws ClassNotFoundException, NumberFormatException {
		UMLActivityDiagram_2115832996 m = new UMLActivityDiagram_2115832996("org.argouml.uml.diagram.activity.ui.UMLActivityDiagram");
		m.monitor();
	}
	private void getRelocationCandidatesUMLActivityDiagram_1758469639() throws ClassNotFoundException, NumberFormatException {
		UMLActivityDiagram_1758469639 m = new UMLActivityDiagram_1758469639("org.argouml.uml.diagram.activity.ui.UMLActivityDiagram");
		m.monitor();
	}
	private void getDragDependenciesFigPartition_1617146438() throws ClassNotFoundException, NumberFormatException {
		FigPartition_1617146438 m = new FigPartition_1617146438("org.argouml.uml.diagram.activity.ui.FigPartition");
		m.monitor();
	}
	private void getActionSubactivityStateUMLActivityDiagram_1823949299() throws ClassNotFoundException, NumberFormatException {
		UMLActivityDiagram_1823949299 m = new UMLActivityDiagram_1823949299("org.argouml.uml.diagram.activity.ui.UMLActivityDiagram");
		m.monitor();
	}
	private void modelChangedFigObjectFlowState_1892591522() throws ClassNotFoundException, NumberFormatException {
		FigObjectFlowState_1892591522 m = new FigObjectFlowState_1892591522("org.argouml.uml.diagram.activity.ui.FigObjectFlowState");
		m.monitor();
	}
	private void setFillColorFigPartition_1480666308() throws ClassNotFoundException, NumberFormatException {
		FigPartition_1480666308 m = new FigPartition_1480666308("org.argouml.uml.diagram.activity.ui.FigPartition");
		m.monitor();
	}
	private void hitHandleFigPartition$SelectionPartition_1410860176() throws ClassNotFoundException, NumberFormatException {
		FigPartition$SelectionPartition_1410860176 m = new FigPartition$SelectionPartition_1410860176("org.argouml.uml.diagram.activity.ui.FigPartition$SelectionPartition");
		m.monitor();
	}
	private void setLineColorFigPartition_800477427() throws ClassNotFoundException, NumberFormatException {
		FigPartition_800477427 m = new FigPartition_800477427("org.argouml.uml.diagram.activity.ui.FigPartition");
		m.monitor();
	}
	private void setFillColorFigActionState_1973580437() throws ClassNotFoundException, NumberFormatException {
		FigActionState_1973580437 m = new FigActionState_1973580437("org.argouml.uml.diagram.activity.ui.FigActionState");
		m.monitor();
	}
	private void createBigPortFigFigPartition_1335031698() throws ClassNotFoundException, NumberFormatException {
		FigPartition_1335031698 m = new FigPartition_1335031698("org.argouml.uml.diagram.activity.ui.FigPartition");
		m.monitor();
	}
	private void changePartitionUMLActivityDiagram_634363631() throws ClassNotFoundException, NumberFormatException {
		UMLActivityDiagram_634363631 m = new UMLActivityDiagram_634363631("org.argouml.uml.diagram.activity.ui.UMLActivityDiagram");
		m.monitor();
	}
	private void setStandardBoundsFigObjectFlowState_1343574302() throws ClassNotFoundException, NumberFormatException {
		FigObjectFlowState_1343574302 m = new FigObjectFlowState_1343574302("org.argouml.uml.diagram.activity.ui.FigObjectFlowState");
		m.monitor();
	}
	private void getActionCallStateUMLActivityDiagram_187627194() throws ClassNotFoundException, NumberFormatException {
		UMLActivityDiagram_187627194 m = new UMLActivityDiagram_187627194("org.argouml.uml.diagram.activity.ui.UMLActivityDiagram");
		m.monitor();
	}
	private void getMinimumSizeFigActionState_988386457() throws ClassNotFoundException, NumberFormatException {
		FigActionState_988386457 m = new FigActionState_988386457("org.argouml.uml.diagram.activity.ui.FigActionState");
		m.monitor();
	}

	protected String expression(String path, String type) {
		if (containsHashCode(path))
			path = path.replace("hashCode()", "hashCode"); 
		if (path.startsWith("[")){
			return sfh.expression(path, type);
		} else {
			return fh.expression(path, type);
		}
	}
	
	protected boolean containsHashCode(String path) {
		if (path.contains("hashCode()")) 
			return true;
		return false;
	}

	protected char parseChar(String s) {
		return s.charAt(0);
	}
	
	protected Integer parseBoolean(String s) {
		return s.equals("true") ? 1 : 0;
	}

}
