library(evaluate)

cbr1Probability <- 1.00

replay(evaluate(file("HelperFunctions.R")))

replay(evaluate(file("T1.R")))
replay(evaluate(file("T2.R")))
replay(evaluate(file("T3.R")))
replay(evaluate(file("T4.R")))
replay(evaluate(file("T5.R")))
replay(evaluate(file("T6.R")))
replay(evaluate(file("T7.R")))
replay(evaluate(file("T8.R")))
replay(evaluate(file("T9.R")))
replay(evaluate(file("T10.R")))
replay(evaluate(file("T11.R")))
replay(evaluate(file("T12.R")))
replay(evaluate(file("T13.R")))
replay(evaluate(file("T14.R")))
replay(evaluate(file("T15.R")))
replay(evaluate(file("T16.R")))
replay(evaluate(file("T17.R")))
replay(evaluate(file("T18.R")))
replay(evaluate(file("T19.R")))
replay(evaluate(file("T20.R")))
replay(evaluate(file("T21.R")))
replay(evaluate(file("T22.R")))
replay(evaluate(file("T23.R")))
replay(evaluate(file("T24.R")))
replay(evaluate(file("T25.R")))

