srtNoMonAverageContinuous <- list()
srtNoMonAverageContinuous <- append(srtNoMonAverageContinuous,returnSRTTimes(srtNoMonAverage_T1,indexesActionsByType_T1, "continuous"))
srtNoMonAverageContinuous <- append(srtNoMonAverageContinuous,returnSRTTimes(srtNoMonAverage_T2,indexesActionsByType_T2, "continuous"))
srtNoMonAverageContinuous <- append(srtNoMonAverageContinuous,returnSRTTimes(srtNoMonAverage_T3,indexesActionsByType_T3, "continuous"))
srtNoMonAverageContinuous <- append(srtNoMonAverageContinuous,returnSRTTimes(srtNoMonAverage_T4,indexesActionsByType_T4, "continuous"))
srtNoMonAverageContinuous <- append(srtNoMonAverageContinuous,returnSRTTimes(srtNoMonAverage_T5,indexesActionsByType_T5, "continuous"))
srtNoMonAverageContinuous <- append(srtNoMonAverageContinuous,returnSRTTimes(srtNoMonAverage_T6,indexesActionsByType_T6, "continuous"))
srtNoMonAverageContinuous <- append(srtNoMonAverageContinuous,returnSRTTimes(srtNoMonAverage_T7,indexesActionsByType_T7, "continuous"))
srtNoMonAverageContinuous <- append(srtNoMonAverageContinuous,returnSRTTimes(srtNoMonAverage_T8,indexesActionsByType_T8, "continuous"))
srtNoMonAverageContinuous <- append(srtNoMonAverageContinuous,returnSRTTimes(srtNoMonAverage_T9,indexesActionsByType_T9, "continuous"))
srtNoMonAverageContinuous <- append(srtNoMonAverageContinuous,returnSRTTimes(srtNoMonAverage_T10,indexesActionsByType_T10, "continuous"))
srtNoMonAverageContinuous <- append(srtNoMonAverageContinuous,returnSRTTimes(srtNoMonAverage_T11,indexesActionsByType_T11, "continuous"))
srtNoMonAverageContinuous <- append(srtNoMonAverageContinuous,returnSRTTimes(srtNoMonAverage_T12,indexesActionsByType_T12, "continuous"))
srtNoMonAverageContinuous <- append(srtNoMonAverageContinuous,returnSRTTimes(srtNoMonAverage_T13,indexesActionsByType_T13, "continuous"))
srtNoMonAverageContinuous <- append(srtNoMonAverageContinuous,returnSRTTimes(srtNoMonAverage_T14,indexesActionsByType_T14, "continuous"))
srtNoMonAverageContinuous <- append(srtNoMonAverageContinuous,returnSRTTimes(srtNoMonAverage_T15,indexesActionsByType_T15, "continuous"))
srtNoMonAverageContinuous <- append(srtNoMonAverageContinuous,returnSRTTimes(srtNoMonAverage_T16,indexesActionsByType_T16, "continuous"))
srtNoMonAverageContinuous <- append(srtNoMonAverageContinuous,returnSRTTimes(srtNoMonAverage_T17,indexesActionsByType_T17, "continuous"))
srtNoMonAverageContinuous <- append(srtNoMonAverageContinuous,returnSRTTimes(srtNoMonAverage_T18,indexesActionsByType_T18, "continuous"))
srtNoMonAverageContinuous <- append(srtNoMonAverageContinuous,returnSRTTimes(srtNoMonAverage_T19,indexesActionsByType_T19, "continuous"))
srtNoMonAverageContinuous <- append(srtNoMonAverageContinuous,returnSRTTimes(srtNoMonAverage_T20,indexesActionsByType_T20, "continuous"))
srtNoMonAverageContinuous <- append(srtNoMonAverageContinuous,returnSRTTimes(srtNoMonAverage_T21,indexesActionsByType_T21, "continuous"))
srtNoMonAverageContinuous <- append(srtNoMonAverageContinuous,returnSRTTimes(srtNoMonAverage_T22,indexesActionsByType_T22, "continuous"))
srtNoMonAverageContinuous <- append(srtNoMonAverageContinuous,returnSRTTimes(srtNoMonAverage_T23,indexesActionsByType_T23, "continuous"))
srtNoMonAverageContinuous <- append(srtNoMonAverageContinuous,returnSRTTimes(srtNoMonAverage_T24,indexesActionsByType_T24, "continuous"))
srtNoMonAverageContinuous <- append(srtNoMonAverageContinuous,returnSRTTimes(srtNoMonAverage_T25,indexesActionsByType_T25, "continuous"))
srtNoMonAverageContinuous <- unlist(srtNoMonAverageContinuous, recursive = FALSE)

srtCBR1AverageContinuous <- list()
srtCBR1AverageContinuous <- append(srtCBR1AverageContinuous,returnSRTTimes(srtCBR1Average_T1,indexesActionsByType_T1, "continuous"))
srtCBR1AverageContinuous <- append(srtCBR1AverageContinuous,returnSRTTimes(srtCBR1Average_T2,indexesActionsByType_T2, "continuous"))
srtCBR1AverageContinuous <- append(srtCBR1AverageContinuous,returnSRTTimes(srtCBR1Average_T3,indexesActionsByType_T3, "continuous"))
srtCBR1AverageContinuous <- append(srtCBR1AverageContinuous,returnSRTTimes(srtCBR1Average_T4,indexesActionsByType_T4, "continuous"))
srtCBR1AverageContinuous <- append(srtCBR1AverageContinuous,returnSRTTimes(srtCBR1Average_T5,indexesActionsByType_T5, "continuous"))
srtCBR1AverageContinuous <- append(srtCBR1AverageContinuous,returnSRTTimes(srtCBR1Average_T6,indexesActionsByType_T6, "continuous"))
srtCBR1AverageContinuous <- append(srtCBR1AverageContinuous,returnSRTTimes(srtCBR1Average_T7,indexesActionsByType_T7, "continuous"))
srtCBR1AverageContinuous <- append(srtCBR1AverageContinuous,returnSRTTimes(srtCBR1Average_T8,indexesActionsByType_T8, "continuous"))
srtCBR1AverageContinuous <- append(srtCBR1AverageContinuous,returnSRTTimes(srtCBR1Average_T9,indexesActionsByType_T9, "continuous"))
srtCBR1AverageContinuous <- append(srtCBR1AverageContinuous,returnSRTTimes(srtCBR1Average_T10,indexesActionsByType_T10, "continuous"))
srtCBR1AverageContinuous <- append(srtCBR1AverageContinuous,returnSRTTimes(srtCBR1Average_T11,indexesActionsByType_T11, "continuous"))
srtCBR1AverageContinuous <- append(srtCBR1AverageContinuous,returnSRTTimes(srtCBR1Average_T12,indexesActionsByType_T12, "continuous"))
srtCBR1AverageContinuous <- append(srtCBR1AverageContinuous,returnSRTTimes(srtCBR1Average_T13,indexesActionsByType_T13, "continuous"))
srtCBR1AverageContinuous <- append(srtCBR1AverageContinuous,returnSRTTimes(srtCBR1Average_T14,indexesActionsByType_T14, "continuous"))
srtCBR1AverageContinuous <- append(srtCBR1AverageContinuous,returnSRTTimes(srtCBR1Average_T15,indexesActionsByType_T15, "continuous"))
srtCBR1AverageContinuous <- append(srtCBR1AverageContinuous,returnSRTTimes(srtCBR1Average_T16,indexesActionsByType_T16, "continuous"))
srtCBR1AverageContinuous <- append(srtCBR1AverageContinuous,returnSRTTimes(srtCBR1Average_T17,indexesActionsByType_T17, "continuous"))
srtCBR1AverageContinuous <- append(srtCBR1AverageContinuous,returnSRTTimes(srtCBR1Average_T18,indexesActionsByType_T18, "continuous"))
srtCBR1AverageContinuous <- append(srtCBR1AverageContinuous,returnSRTTimes(srtCBR1Average_T19,indexesActionsByType_T19, "continuous"))
srtCBR1AverageContinuous <- append(srtCBR1AverageContinuous,returnSRTTimes(srtCBR1Average_T20,indexesActionsByType_T20, "continuous"))
srtCBR1AverageContinuous <- append(srtCBR1AverageContinuous,returnSRTTimes(srtCBR1Average_T21,indexesActionsByType_T21, "continuous"))
srtCBR1AverageContinuous <- append(srtCBR1AverageContinuous,returnSRTTimes(srtCBR1Average_T22,indexesActionsByType_T22, "continuous"))
srtCBR1AverageContinuous <- append(srtCBR1AverageContinuous,returnSRTTimes(srtCBR1Average_T23,indexesActionsByType_T23, "continuous"))
srtCBR1AverageContinuous <- append(srtCBR1AverageContinuous,returnSRTTimes(srtCBR1Average_T24,indexesActionsByType_T24, "continuous"))
srtCBR1AverageContinuous <- append(srtCBR1AverageContinuous,returnSRTTimes(srtCBR1Average_T25,indexesActionsByType_T25, "continuous"))
srtCBR1AverageContinuous <- unlist(srtCBR1AverageContinuous, recursive = FALSE)

srtSampler1AverageContinuous <- list()
srtSampler1AverageContinuous <- append(srtSampler1AverageContinuous,returnSRTTimes(srtSampler1Average_T1,indexesActionsByType_T1, "continuous"))
srtSampler1AverageContinuous <- append(srtSampler1AverageContinuous,returnSRTTimes(srtSampler1Average_T2,indexesActionsByType_T2, "continuous"))
srtSampler1AverageContinuous <- append(srtSampler1AverageContinuous,returnSRTTimes(srtSampler1Average_T3,indexesActionsByType_T3, "continuous"))
srtSampler1AverageContinuous <- append(srtSampler1AverageContinuous,returnSRTTimes(srtSampler1Average_T4,indexesActionsByType_T4, "continuous"))
srtSampler1AverageContinuous <- append(srtSampler1AverageContinuous,returnSRTTimes(srtSampler1Average_T5,indexesActionsByType_T5, "continuous"))
srtSampler1AverageContinuous <- append(srtSampler1AverageContinuous,returnSRTTimes(srtSampler1Average_T6,indexesActionsByType_T6, "continuous"))
srtSampler1AverageContinuous <- append(srtSampler1AverageContinuous,returnSRTTimes(srtSampler1Average_T7,indexesActionsByType_T7, "continuous"))
srtSampler1AverageContinuous <- append(srtSampler1AverageContinuous,returnSRTTimes(srtSampler1Average_T8,indexesActionsByType_T8, "continuous"))
srtSampler1AverageContinuous <- append(srtSampler1AverageContinuous,returnSRTTimes(srtSampler1Average_T9,indexesActionsByType_T9, "continuous"))
srtSampler1AverageContinuous <- append(srtSampler1AverageContinuous,returnSRTTimes(srtSampler1Average_T10,indexesActionsByType_T10, "continuous"))
srtSampler1AverageContinuous <- append(srtSampler1AverageContinuous,returnSRTTimes(srtSampler1Average_T11,indexesActionsByType_T11, "continuous"))
srtSampler1AverageContinuous <- append(srtSampler1AverageContinuous,returnSRTTimes(srtSampler1Average_T12,indexesActionsByType_T12, "continuous"))
srtSampler1AverageContinuous <- append(srtSampler1AverageContinuous,returnSRTTimes(srtSampler1Average_T13,indexesActionsByType_T13, "continuous"))
srtSampler1AverageContinuous <- append(srtSampler1AverageContinuous,returnSRTTimes(srtSampler1Average_T14,indexesActionsByType_T14, "continuous"))
srtSampler1AverageContinuous <- append(srtSampler1AverageContinuous,returnSRTTimes(srtSampler1Average_T15,indexesActionsByType_T15, "continuous"))
srtSampler1AverageContinuous <- append(srtSampler1AverageContinuous,returnSRTTimes(srtSampler1Average_T16,indexesActionsByType_T16, "continuous"))
srtSampler1AverageContinuous <- append(srtSampler1AverageContinuous,returnSRTTimes(srtSampler1Average_T17,indexesActionsByType_T17, "continuous"))
srtSampler1AverageContinuous <- append(srtSampler1AverageContinuous,returnSRTTimes(srtSampler1Average_T18,indexesActionsByType_T18, "continuous"))
srtSampler1AverageContinuous <- append(srtSampler1AverageContinuous,returnSRTTimes(srtSampler1Average_T19,indexesActionsByType_T19, "continuous"))
srtSampler1AverageContinuous <- append(srtSampler1AverageContinuous,returnSRTTimes(srtSampler1Average_T20,indexesActionsByType_T20, "continuous"))
srtSampler1AverageContinuous <- append(srtSampler1AverageContinuous,returnSRTTimes(srtSampler1Average_T21,indexesActionsByType_T21, "continuous"))
srtSampler1AverageContinuous <- append(srtSampler1AverageContinuous,returnSRTTimes(srtSampler1Average_T22,indexesActionsByType_T22, "continuous"))
srtSampler1AverageContinuous <- append(srtSampler1AverageContinuous,returnSRTTimes(srtSampler1Average_T23,indexesActionsByType_T23, "continuous"))
srtSampler1AverageContinuous <- append(srtSampler1AverageContinuous,returnSRTTimes(srtSampler1Average_T24,indexesActionsByType_T24, "continuous"))
srtSampler1AverageContinuous <- append(srtSampler1AverageContinuous,returnSRTTimes(srtSampler1Average_T25,indexesActionsByType_T25, "continuous"))
srtSampler1AverageContinuous <- unlist(srtSampler1AverageContinuous, recursive = FALSE)

srtSampler2AverageContinuous <- list()
srtSampler2AverageContinuous <- append(srtSampler2AverageContinuous,returnSRTTimes(srtSampler2Average_T1,indexesActionsByType_T1, "continuous"))
srtSampler2AverageContinuous <- append(srtSampler2AverageContinuous,returnSRTTimes(srtSampler2Average_T2,indexesActionsByType_T2, "continuous"))
srtSampler2AverageContinuous <- append(srtSampler2AverageContinuous,returnSRTTimes(srtSampler2Average_T3,indexesActionsByType_T3, "continuous"))
srtSampler2AverageContinuous <- append(srtSampler2AverageContinuous,returnSRTTimes(srtSampler2Average_T4,indexesActionsByType_T4, "continuous"))
srtSampler2AverageContinuous <- append(srtSampler2AverageContinuous,returnSRTTimes(srtSampler2Average_T5,indexesActionsByType_T5, "continuous"))
srtSampler2AverageContinuous <- append(srtSampler2AverageContinuous,returnSRTTimes(srtSampler2Average_T6,indexesActionsByType_T6, "continuous"))
srtSampler2AverageContinuous <- append(srtSampler2AverageContinuous,returnSRTTimes(srtSampler2Average_T7,indexesActionsByType_T7, "continuous"))
srtSampler2AverageContinuous <- append(srtSampler2AverageContinuous,returnSRTTimes(srtSampler2Average_T8,indexesActionsByType_T8, "continuous"))
srtSampler2AverageContinuous <- append(srtSampler2AverageContinuous,returnSRTTimes(srtSampler2Average_T9,indexesActionsByType_T9, "continuous"))
srtSampler2AverageContinuous <- append(srtSampler2AverageContinuous,returnSRTTimes(srtSampler2Average_T10,indexesActionsByType_T10, "continuous"))
srtSampler2AverageContinuous <- append(srtSampler2AverageContinuous,returnSRTTimes(srtSampler2Average_T11,indexesActionsByType_T11, "continuous"))
srtSampler2AverageContinuous <- append(srtSampler2AverageContinuous,returnSRTTimes(srtSampler2Average_T12,indexesActionsByType_T12, "continuous"))
srtSampler2AverageContinuous <- append(srtSampler2AverageContinuous,returnSRTTimes(srtSampler2Average_T13,indexesActionsByType_T13, "continuous"))
srtSampler2AverageContinuous <- append(srtSampler2AverageContinuous,returnSRTTimes(srtSampler2Average_T14,indexesActionsByType_T14, "continuous"))
srtSampler2AverageContinuous <- append(srtSampler2AverageContinuous,returnSRTTimes(srtSampler2Average_T15,indexesActionsByType_T15, "continuous"))
srtSampler2AverageContinuous <- append(srtSampler2AverageContinuous,returnSRTTimes(srtSampler2Average_T16,indexesActionsByType_T16, "continuous"))
srtSampler2AverageContinuous <- append(srtSampler2AverageContinuous,returnSRTTimes(srtSampler2Average_T17,indexesActionsByType_T17, "continuous"))
srtSampler2AverageContinuous <- append(srtSampler2AverageContinuous,returnSRTTimes(srtSampler2Average_T18,indexesActionsByType_T18, "continuous"))
srtSampler2AverageContinuous <- append(srtSampler2AverageContinuous,returnSRTTimes(srtSampler2Average_T19,indexesActionsByType_T19, "continuous"))
srtSampler2AverageContinuous <- append(srtSampler2AverageContinuous,returnSRTTimes(srtSampler2Average_T20,indexesActionsByType_T20, "continuous"))
srtSampler2AverageContinuous <- append(srtSampler2AverageContinuous,returnSRTTimes(srtSampler2Average_T21,indexesActionsByType_T21, "continuous"))
srtSampler2AverageContinuous <- append(srtSampler2AverageContinuous,returnSRTTimes(srtSampler2Average_T22,indexesActionsByType_T22, "continuous"))
srtSampler2AverageContinuous <- append(srtSampler2AverageContinuous,returnSRTTimes(srtSampler2Average_T23,indexesActionsByType_T23, "continuous"))
srtSampler2AverageContinuous <- append(srtSampler2AverageContinuous,returnSRTTimes(srtSampler2Average_T24,indexesActionsByType_T24, "continuous"))
srtSampler2AverageContinuous <- append(srtSampler2AverageContinuous,returnSRTTimes(srtSampler2Average_T25,indexesActionsByType_T25, "continuous"))
srtSampler2AverageContinuous <- unlist(srtSampler2AverageContinuous, recursive = FALSE)

ohNoMonCBR1Continuous <- overhead(mean(srtNoMonAverageContinuous,na.rm = TRUE),mean(srtCBR1AverageContinuous,na.rm = TRUE))
ohNoMonSampler1Continuous <- overhead(mean(srtNoMonAverageContinuous,na.rm = TRUE),mean(srtSampler1AverageContinuous,na.rm = TRUE))
ohNoMonSampler2Continuous <- overhead(mean(srtNoMonAverageContinuous,na.rm = TRUE),mean(srtSampler2AverageContinuous,na.rm = TRUE))


cat("ohNoMonCBR1Continuous: ", ohNoMonCBR1Continuous, "%\n")

cat("ohNoMonSampler1Continuous: ", ohNoMonSampler1Continuous, "%\n")

cat("ohNoMonSampler2Continuous: ", ohNoMonSampler2Continuous, "%\n")
