srtNoMonAverageImmediate <- list()
srtNoMonAverageImmediate <- append(srtNoMonAverageImmediate,returnSRTTimes(srtNoMonAverage_T1,indexesActionsByType_T1, "immediate"))
srtNoMonAverageImmediate <- append(srtNoMonAverageImmediate,returnSRTTimes(srtNoMonAverage_T2,indexesActionsByType_T2, "immediate"))
srtNoMonAverageImmediate <- append(srtNoMonAverageImmediate,returnSRTTimes(srtNoMonAverage_T3,indexesActionsByType_T3, "immediate"))
srtNoMonAverageImmediate <- append(srtNoMonAverageImmediate,returnSRTTimes(srtNoMonAverage_T4,indexesActionsByType_T4, "immediate"))
srtNoMonAverageImmediate <- append(srtNoMonAverageImmediate,returnSRTTimes(srtNoMonAverage_T5,indexesActionsByType_T5, "immediate"))
srtNoMonAverageImmediate <- append(srtNoMonAverageImmediate,returnSRTTimes(srtNoMonAverage_T6,indexesActionsByType_T6, "immediate"))
srtNoMonAverageImmediate <- append(srtNoMonAverageImmediate,returnSRTTimes(srtNoMonAverage_T7,indexesActionsByType_T7, "immediate"))
srtNoMonAverageImmediate <- append(srtNoMonAverageImmediate,returnSRTTimes(srtNoMonAverage_T8,indexesActionsByType_T8, "immediate"))
srtNoMonAverageImmediate <- append(srtNoMonAverageImmediate,returnSRTTimes(srtNoMonAverage_T9,indexesActionsByType_T9, "immediate"))
srtNoMonAverageImmediate <- append(srtNoMonAverageImmediate,returnSRTTimes(srtNoMonAverage_T10,indexesActionsByType_T10, "immediate"))
srtNoMonAverageImmediate <- append(srtNoMonAverageImmediate,returnSRTTimes(srtNoMonAverage_T11,indexesActionsByType_T11, "immediate"))
srtNoMonAverageImmediate <- append(srtNoMonAverageImmediate,returnSRTTimes(srtNoMonAverage_T12,indexesActionsByType_T12, "immediate"))
srtNoMonAverageImmediate <- append(srtNoMonAverageImmediate,returnSRTTimes(srtNoMonAverage_T13,indexesActionsByType_T13, "immediate"))
srtNoMonAverageImmediate <- append(srtNoMonAverageImmediate,returnSRTTimes(srtNoMonAverage_T14,indexesActionsByType_T14, "immediate"))
srtNoMonAverageImmediate <- append(srtNoMonAverageImmediate,returnSRTTimes(srtNoMonAverage_T15,indexesActionsByType_T15, "immediate"))
srtNoMonAverageImmediate <- append(srtNoMonAverageImmediate,returnSRTTimes(srtNoMonAverage_T16,indexesActionsByType_T16, "immediate"))
srtNoMonAverageImmediate <- append(srtNoMonAverageImmediate,returnSRTTimes(srtNoMonAverage_T17,indexesActionsByType_T17, "immediate"))
srtNoMonAverageImmediate <- append(srtNoMonAverageImmediate,returnSRTTimes(srtNoMonAverage_T18,indexesActionsByType_T18, "immediate"))
srtNoMonAverageImmediate <- append(srtNoMonAverageImmediate,returnSRTTimes(srtNoMonAverage_T19,indexesActionsByType_T19, "immediate"))
srtNoMonAverageImmediate <- append(srtNoMonAverageImmediate,returnSRTTimes(srtNoMonAverage_T20,indexesActionsByType_T20, "immediate"))
srtNoMonAverageImmediate <- append(srtNoMonAverageImmediate,returnSRTTimes(srtNoMonAverage_T21,indexesActionsByType_T21, "immediate"))
srtNoMonAverageImmediate <- append(srtNoMonAverageImmediate,returnSRTTimes(srtNoMonAverage_T22,indexesActionsByType_T22, "immediate"))
srtNoMonAverageImmediate <- append(srtNoMonAverageImmediate,returnSRTTimes(srtNoMonAverage_T23,indexesActionsByType_T23, "immediate"))
srtNoMonAverageImmediate <- append(srtNoMonAverageImmediate,returnSRTTimes(srtNoMonAverage_T24,indexesActionsByType_T24, "immediate"))
srtNoMonAverageImmediate <- append(srtNoMonAverageImmediate,returnSRTTimes(srtNoMonAverage_T25,indexesActionsByType_T25, "immediate"))
srtNoMonAverageImmediate <- unlist(srtNoMonAverageImmediate, recursive = FALSE)

srtCBR1AverageImmediate <- list()
srtCBR1AverageImmediate <- append(srtCBR1AverageImmediate,returnSRTTimes(srtCBR1Average_T1,indexesActionsByType_T1, "immediate"))
srtCBR1AverageImmediate <- append(srtCBR1AverageImmediate,returnSRTTimes(srtCBR1Average_T2,indexesActionsByType_T2, "immediate"))
srtCBR1AverageImmediate <- append(srtCBR1AverageImmediate,returnSRTTimes(srtCBR1Average_T3,indexesActionsByType_T3, "immediate"))
srtCBR1AverageImmediate <- append(srtCBR1AverageImmediate,returnSRTTimes(srtCBR1Average_T4,indexesActionsByType_T4, "immediate"))
srtCBR1AverageImmediate <- append(srtCBR1AverageImmediate,returnSRTTimes(srtCBR1Average_T5,indexesActionsByType_T5, "immediate"))
srtCBR1AverageImmediate <- append(srtCBR1AverageImmediate,returnSRTTimes(srtCBR1Average_T6,indexesActionsByType_T6, "immediate"))
srtCBR1AverageImmediate <- append(srtCBR1AverageImmediate,returnSRTTimes(srtCBR1Average_T7,indexesActionsByType_T7, "immediate"))
srtCBR1AverageImmediate <- append(srtCBR1AverageImmediate,returnSRTTimes(srtCBR1Average_T8,indexesActionsByType_T8, "immediate"))
srtCBR1AverageImmediate <- append(srtCBR1AverageImmediate,returnSRTTimes(srtCBR1Average_T9,indexesActionsByType_T9, "immediate"))
srtCBR1AverageImmediate <- append(srtCBR1AverageImmediate,returnSRTTimes(srtCBR1Average_T10,indexesActionsByType_T10, "immediate"))
srtCBR1AverageImmediate <- append(srtCBR1AverageImmediate,returnSRTTimes(srtCBR1Average_T11,indexesActionsByType_T11, "immediate"))
srtCBR1AverageImmediate <- append(srtCBR1AverageImmediate,returnSRTTimes(srtCBR1Average_T12,indexesActionsByType_T12, "immediate"))
srtCBR1AverageImmediate <- append(srtCBR1AverageImmediate,returnSRTTimes(srtCBR1Average_T13,indexesActionsByType_T13, "immediate"))
srtCBR1AverageImmediate <- append(srtCBR1AverageImmediate,returnSRTTimes(srtCBR1Average_T14,indexesActionsByType_T14, "immediate"))
srtCBR1AverageImmediate <- append(srtCBR1AverageImmediate,returnSRTTimes(srtCBR1Average_T15,indexesActionsByType_T15, "immediate"))
srtCBR1AverageImmediate <- append(srtCBR1AverageImmediate,returnSRTTimes(srtCBR1Average_T16,indexesActionsByType_T16, "immediate"))
srtCBR1AverageImmediate <- append(srtCBR1AverageImmediate,returnSRTTimes(srtCBR1Average_T17,indexesActionsByType_T17, "immediate"))
srtCBR1AverageImmediate <- append(srtCBR1AverageImmediate,returnSRTTimes(srtCBR1Average_T18,indexesActionsByType_T18, "immediate"))
srtCBR1AverageImmediate <- append(srtCBR1AverageImmediate,returnSRTTimes(srtCBR1Average_T19,indexesActionsByType_T19, "immediate"))
srtCBR1AverageImmediate <- append(srtCBR1AverageImmediate,returnSRTTimes(srtCBR1Average_T20,indexesActionsByType_T20, "immediate"))
srtCBR1AverageImmediate <- append(srtCBR1AverageImmediate,returnSRTTimes(srtCBR1Average_T21,indexesActionsByType_T21, "immediate"))
srtCBR1AverageImmediate <- append(srtCBR1AverageImmediate,returnSRTTimes(srtCBR1Average_T22,indexesActionsByType_T22, "immediate"))
srtCBR1AverageImmediate <- append(srtCBR1AverageImmediate,returnSRTTimes(srtCBR1Average_T23,indexesActionsByType_T23, "immediate"))
srtCBR1AverageImmediate <- append(srtCBR1AverageImmediate,returnSRTTimes(srtCBR1Average_T24,indexesActionsByType_T24, "immediate"))
srtCBR1AverageImmediate <- append(srtCBR1AverageImmediate,returnSRTTimes(srtCBR1Average_T25,indexesActionsByType_T25, "immediate"))
srtCBR1AverageImmediate <- unlist(srtCBR1AverageImmediate, recursive = FALSE)

srtSampler1AverageImmediate <- list()
srtSampler1AverageImmediate <- append(srtSampler1AverageImmediate,returnSRTTimes(srtSampler1Average_T1,indexesActionsByType_T1, "immediate"))
srtSampler1AverageImmediate <- append(srtSampler1AverageImmediate,returnSRTTimes(srtSampler1Average_T2,indexesActionsByType_T2, "immediate"))
srtSampler1AverageImmediate <- append(srtSampler1AverageImmediate,returnSRTTimes(srtSampler1Average_T3,indexesActionsByType_T3, "immediate"))
srtSampler1AverageImmediate <- append(srtSampler1AverageImmediate,returnSRTTimes(srtSampler1Average_T4,indexesActionsByType_T4, "immediate"))
srtSampler1AverageImmediate <- append(srtSampler1AverageImmediate,returnSRTTimes(srtSampler1Average_T5,indexesActionsByType_T5, "immediate"))
srtSampler1AverageImmediate <- append(srtSampler1AverageImmediate,returnSRTTimes(srtSampler1Average_T6,indexesActionsByType_T6, "immediate"))
srtSampler1AverageImmediate <- append(srtSampler1AverageImmediate,returnSRTTimes(srtSampler1Average_T7,indexesActionsByType_T7, "immediate"))
srtSampler1AverageImmediate <- append(srtSampler1AverageImmediate,returnSRTTimes(srtSampler1Average_T8,indexesActionsByType_T8, "immediate"))
srtSampler1AverageImmediate <- append(srtSampler1AverageImmediate,returnSRTTimes(srtSampler1Average_T9,indexesActionsByType_T9, "immediate"))
srtSampler1AverageImmediate <- append(srtSampler1AverageImmediate,returnSRTTimes(srtSampler1Average_T10,indexesActionsByType_T10, "immediate"))
srtSampler1AverageImmediate <- append(srtSampler1AverageImmediate,returnSRTTimes(srtSampler1Average_T11,indexesActionsByType_T11, "immediate"))
srtSampler1AverageImmediate <- append(srtSampler1AverageImmediate,returnSRTTimes(srtSampler1Average_T12,indexesActionsByType_T12, "immediate"))
srtSampler1AverageImmediate <- append(srtSampler1AverageImmediate,returnSRTTimes(srtSampler1Average_T13,indexesActionsByType_T13, "immediate"))
srtSampler1AverageImmediate <- append(srtSampler1AverageImmediate,returnSRTTimes(srtSampler1Average_T14,indexesActionsByType_T14, "immediate"))
srtSampler1AverageImmediate <- append(srtSampler1AverageImmediate,returnSRTTimes(srtSampler1Average_T15,indexesActionsByType_T15, "immediate"))
srtSampler1AverageImmediate <- append(srtSampler1AverageImmediate,returnSRTTimes(srtSampler1Average_T16,indexesActionsByType_T16, "immediate"))
srtSampler1AverageImmediate <- append(srtSampler1AverageImmediate,returnSRTTimes(srtSampler1Average_T17,indexesActionsByType_T17, "immediate"))
srtSampler1AverageImmediate <- append(srtSampler1AverageImmediate,returnSRTTimes(srtSampler1Average_T18,indexesActionsByType_T18, "immediate"))
srtSampler1AverageImmediate <- append(srtSampler1AverageImmediate,returnSRTTimes(srtSampler1Average_T19,indexesActionsByType_T19, "immediate"))
srtSampler1AverageImmediate <- append(srtSampler1AverageImmediate,returnSRTTimes(srtSampler1Average_T20,indexesActionsByType_T20, "immediate"))
srtSampler1AverageImmediate <- append(srtSampler1AverageImmediate,returnSRTTimes(srtSampler1Average_T21,indexesActionsByType_T21, "immediate"))
srtSampler1AverageImmediate <- append(srtSampler1AverageImmediate,returnSRTTimes(srtSampler1Average_T22,indexesActionsByType_T22, "immediate"))
srtSampler1AverageImmediate <- append(srtSampler1AverageImmediate,returnSRTTimes(srtSampler1Average_T23,indexesActionsByType_T23, "immediate"))
srtSampler1AverageImmediate <- append(srtSampler1AverageImmediate,returnSRTTimes(srtSampler1Average_T24,indexesActionsByType_T24, "immediate"))
srtSampler1AverageImmediate <- append(srtSampler1AverageImmediate,returnSRTTimes(srtSampler1Average_T25,indexesActionsByType_T25, "immediate"))
srtSampler1AverageImmediate <- unlist(srtSampler1AverageImmediate, recursive = FALSE)

srtSampler2AverageImmediate <- list()
srtSampler2AverageImmediate <- append(srtSampler2AverageImmediate,returnSRTTimes(srtSampler2Average_T1,indexesActionsByType_T1, "immediate"))
srtSampler2AverageImmediate <- append(srtSampler2AverageImmediate,returnSRTTimes(srtSampler2Average_T2,indexesActionsByType_T2, "immediate"))
srtSampler2AverageImmediate <- append(srtSampler2AverageImmediate,returnSRTTimes(srtSampler2Average_T3,indexesActionsByType_T3, "immediate"))
srtSampler2AverageImmediate <- append(srtSampler2AverageImmediate,returnSRTTimes(srtSampler2Average_T4,indexesActionsByType_T4, "immediate"))
srtSampler2AverageImmediate <- append(srtSampler2AverageImmediate,returnSRTTimes(srtSampler2Average_T5,indexesActionsByType_T5, "immediate"))
srtSampler2AverageImmediate <- append(srtSampler2AverageImmediate,returnSRTTimes(srtSampler2Average_T6,indexesActionsByType_T6, "immediate"))
srtSampler2AverageImmediate <- append(srtSampler2AverageImmediate,returnSRTTimes(srtSampler2Average_T7,indexesActionsByType_T7, "immediate"))
srtSampler2AverageImmediate <- append(srtSampler2AverageImmediate,returnSRTTimes(srtSampler2Average_T8,indexesActionsByType_T8, "immediate"))
srtSampler2AverageImmediate <- append(srtSampler2AverageImmediate,returnSRTTimes(srtSampler2Average_T9,indexesActionsByType_T9, "immediate"))
srtSampler2AverageImmediate <- append(srtSampler2AverageImmediate,returnSRTTimes(srtSampler2Average_T10,indexesActionsByType_T10, "immediate"))
srtSampler2AverageImmediate <- append(srtSampler2AverageImmediate,returnSRTTimes(srtSampler2Average_T11,indexesActionsByType_T11, "immediate"))
srtSampler2AverageImmediate <- append(srtSampler2AverageImmediate,returnSRTTimes(srtSampler2Average_T12,indexesActionsByType_T12, "immediate"))
srtSampler2AverageImmediate <- append(srtSampler2AverageImmediate,returnSRTTimes(srtSampler2Average_T13,indexesActionsByType_T13, "immediate"))
srtSampler2AverageImmediate <- append(srtSampler2AverageImmediate,returnSRTTimes(srtSampler2Average_T14,indexesActionsByType_T14, "immediate"))
srtSampler2AverageImmediate <- append(srtSampler2AverageImmediate,returnSRTTimes(srtSampler2Average_T15,indexesActionsByType_T15, "immediate"))
srtSampler2AverageImmediate <- append(srtSampler2AverageImmediate,returnSRTTimes(srtSampler2Average_T16,indexesActionsByType_T16, "immediate"))
srtSampler2AverageImmediate <- append(srtSampler2AverageImmediate,returnSRTTimes(srtSampler2Average_T17,indexesActionsByType_T17, "immediate"))
srtSampler2AverageImmediate <- append(srtSampler2AverageImmediate,returnSRTTimes(srtSampler2Average_T18,indexesActionsByType_T18, "immediate"))
srtSampler2AverageImmediate <- append(srtSampler2AverageImmediate,returnSRTTimes(srtSampler2Average_T19,indexesActionsByType_T19, "immediate"))
srtSampler2AverageImmediate <- append(srtSampler2AverageImmediate,returnSRTTimes(srtSampler2Average_T20,indexesActionsByType_T20, "immediate"))
srtSampler2AverageImmediate <- append(srtSampler2AverageImmediate,returnSRTTimes(srtSampler2Average_T21,indexesActionsByType_T21, "immediate"))
srtSampler2AverageImmediate <- append(srtSampler2AverageImmediate,returnSRTTimes(srtSampler2Average_T22,indexesActionsByType_T22, "immediate"))
srtSampler2AverageImmediate <- append(srtSampler2AverageImmediate,returnSRTTimes(srtSampler2Average_T23,indexesActionsByType_T23, "immediate"))
srtSampler2AverageImmediate <- append(srtSampler2AverageImmediate,returnSRTTimes(srtSampler2Average_T24,indexesActionsByType_T24, "immediate"))
srtSampler2AverageImmediate <- append(srtSampler2AverageImmediate,returnSRTTimes(srtSampler2Average_T25,indexesActionsByType_T25, "immediate"))
srtSampler2AverageImmediate <- unlist(srtSampler2AverageImmediate, recursive = FALSE)

ohNoMonCBR1Immediate <- overhead(mean(srtNoMonAverageImmediate,na.rm = TRUE),mean(srtCBR1AverageImmediate,na.rm = TRUE))
ohNoMonSampler1Immediate <- overhead(mean(srtNoMonAverageImmediate,na.rm = TRUE),mean(srtSampler1AverageImmediate,na.rm = TRUE))
ohNoMonSampler2Immediate <- overhead(mean(srtNoMonAverageImmediate,na.rm = TRUE),mean(srtSampler2AverageImmediate,na.rm = TRUE))


cat("ohNoMonCBR1Immediate: ", ohNoMonCBR1Immediate, "%\n")

cat("ohNoMonSampler1Immediate: ", ohNoMonSampler1Immediate, "%\n")

cat("ohNoMonSampler2Immediate: ", ohNoMonSampler2Immediate, "%\n")
