srtNoMonAverageInstantaneous <- list()
srtNoMonAverageInstantaneous <- append(srtNoMonAverageInstantaneous,returnSRTTimes(srtNoMonAverage_T1,indexesActionsByType_T1, "instantaneous"))
srtNoMonAverageInstantaneous <- append(srtNoMonAverageInstantaneous,returnSRTTimes(srtNoMonAverage_T2,indexesActionsByType_T2, "instantaneous"))
srtNoMonAverageInstantaneous <- append(srtNoMonAverageInstantaneous,returnSRTTimes(srtNoMonAverage_T3,indexesActionsByType_T3, "instantaneous"))
srtNoMonAverageInstantaneous <- append(srtNoMonAverageInstantaneous,returnSRTTimes(srtNoMonAverage_T4,indexesActionsByType_T4, "instantaneous"))
srtNoMonAverageInstantaneous <- append(srtNoMonAverageInstantaneous,returnSRTTimes(srtNoMonAverage_T5,indexesActionsByType_T5, "instantaneous"))
srtNoMonAverageInstantaneous <- append(srtNoMonAverageInstantaneous,returnSRTTimes(srtNoMonAverage_T6,indexesActionsByType_T6, "instantaneous"))
srtNoMonAverageInstantaneous <- append(srtNoMonAverageInstantaneous,returnSRTTimes(srtNoMonAverage_T7,indexesActionsByType_T7, "instantaneous"))
srtNoMonAverageInstantaneous <- append(srtNoMonAverageInstantaneous,returnSRTTimes(srtNoMonAverage_T8,indexesActionsByType_T8, "instantaneous"))
srtNoMonAverageInstantaneous <- append(srtNoMonAverageInstantaneous,returnSRTTimes(srtNoMonAverage_T9,indexesActionsByType_T9, "instantaneous"))
srtNoMonAverageInstantaneous <- append(srtNoMonAverageInstantaneous,returnSRTTimes(srtNoMonAverage_T10,indexesActionsByType_T10, "instantaneous"))
srtNoMonAverageInstantaneous <- append(srtNoMonAverageInstantaneous,returnSRTTimes(srtNoMonAverage_T11,indexesActionsByType_T11, "instantaneous"))
srtNoMonAverageInstantaneous <- append(srtNoMonAverageInstantaneous,returnSRTTimes(srtNoMonAverage_T12,indexesActionsByType_T12, "instantaneous"))
srtNoMonAverageInstantaneous <- append(srtNoMonAverageInstantaneous,returnSRTTimes(srtNoMonAverage_T13,indexesActionsByType_T13, "instantaneous"))
srtNoMonAverageInstantaneous <- append(srtNoMonAverageInstantaneous,returnSRTTimes(srtNoMonAverage_T14,indexesActionsByType_T14, "instantaneous"))
srtNoMonAverageInstantaneous <- append(srtNoMonAverageInstantaneous,returnSRTTimes(srtNoMonAverage_T15,indexesActionsByType_T15, "instantaneous"))
srtNoMonAverageInstantaneous <- append(srtNoMonAverageInstantaneous,returnSRTTimes(srtNoMonAverage_T16,indexesActionsByType_T16, "instantaneous"))
srtNoMonAverageInstantaneous <- append(srtNoMonAverageInstantaneous,returnSRTTimes(srtNoMonAverage_T17,indexesActionsByType_T17, "instantaneous"))
srtNoMonAverageInstantaneous <- append(srtNoMonAverageInstantaneous,returnSRTTimes(srtNoMonAverage_T18,indexesActionsByType_T18, "instantaneous"))
srtNoMonAverageInstantaneous <- append(srtNoMonAverageInstantaneous,returnSRTTimes(srtNoMonAverage_T19,indexesActionsByType_T19, "instantaneous"))
srtNoMonAverageInstantaneous <- append(srtNoMonAverageInstantaneous,returnSRTTimes(srtNoMonAverage_T20,indexesActionsByType_T20, "instantaneous"))
srtNoMonAverageInstantaneous <- append(srtNoMonAverageInstantaneous,returnSRTTimes(srtNoMonAverage_T21,indexesActionsByType_T21, "instantaneous"))
srtNoMonAverageInstantaneous <- append(srtNoMonAverageInstantaneous,returnSRTTimes(srtNoMonAverage_T22,indexesActionsByType_T22, "instantaneous"))
srtNoMonAverageInstantaneous <- append(srtNoMonAverageInstantaneous,returnSRTTimes(srtNoMonAverage_T23,indexesActionsByType_T23, "instantaneous"))
srtNoMonAverageInstantaneous <- append(srtNoMonAverageInstantaneous,returnSRTTimes(srtNoMonAverage_T24,indexesActionsByType_T24, "instantaneous"))
srtNoMonAverageInstantaneous <- append(srtNoMonAverageInstantaneous,returnSRTTimes(srtNoMonAverage_T25,indexesActionsByType_T25, "instantaneous"))
srtNoMonAverageInstantaneous <- unlist(srtNoMonAverageInstantaneous, recursive = FALSE)

srtCBR1AverageInstantaneous <- list()
srtCBR1AverageInstantaneous <- append(srtCBR1AverageInstantaneous,returnSRTTimes(srtCBR1Average_T1,indexesActionsByType_T1, "instantaneous"))
srtCBR1AverageInstantaneous <- append(srtCBR1AverageInstantaneous,returnSRTTimes(srtCBR1Average_T2,indexesActionsByType_T2, "instantaneous"))
srtCBR1AverageInstantaneous <- append(srtCBR1AverageInstantaneous,returnSRTTimes(srtCBR1Average_T3,indexesActionsByType_T3, "instantaneous"))
srtCBR1AverageInstantaneous <- append(srtCBR1AverageInstantaneous,returnSRTTimes(srtCBR1Average_T4,indexesActionsByType_T4, "instantaneous"))
srtCBR1AverageInstantaneous <- append(srtCBR1AverageInstantaneous,returnSRTTimes(srtCBR1Average_T5,indexesActionsByType_T5, "instantaneous"))
srtCBR1AverageInstantaneous <- append(srtCBR1AverageInstantaneous,returnSRTTimes(srtCBR1Average_T6,indexesActionsByType_T6, "instantaneous"))
srtCBR1AverageInstantaneous <- append(srtCBR1AverageInstantaneous,returnSRTTimes(srtCBR1Average_T7,indexesActionsByType_T7, "instantaneous"))
srtCBR1AverageInstantaneous <- append(srtCBR1AverageInstantaneous,returnSRTTimes(srtCBR1Average_T8,indexesActionsByType_T8, "instantaneous"))
srtCBR1AverageInstantaneous <- append(srtCBR1AverageInstantaneous,returnSRTTimes(srtCBR1Average_T9,indexesActionsByType_T9, "instantaneous"))
srtCBR1AverageInstantaneous <- append(srtCBR1AverageInstantaneous,returnSRTTimes(srtCBR1Average_T10,indexesActionsByType_T10, "instantaneous"))
srtCBR1AverageInstantaneous <- append(srtCBR1AverageInstantaneous,returnSRTTimes(srtCBR1Average_T11,indexesActionsByType_T11, "instantaneous"))
srtCBR1AverageInstantaneous <- append(srtCBR1AverageInstantaneous,returnSRTTimes(srtCBR1Average_T12,indexesActionsByType_T12, "instantaneous"))
srtCBR1AverageInstantaneous <- append(srtCBR1AverageInstantaneous,returnSRTTimes(srtCBR1Average_T13,indexesActionsByType_T13, "instantaneous"))
srtCBR1AverageInstantaneous <- append(srtCBR1AverageInstantaneous,returnSRTTimes(srtCBR1Average_T14,indexesActionsByType_T14, "instantaneous"))
srtCBR1AverageInstantaneous <- append(srtCBR1AverageInstantaneous,returnSRTTimes(srtCBR1Average_T15,indexesActionsByType_T15, "instantaneous"))
srtCBR1AverageInstantaneous <- append(srtCBR1AverageInstantaneous,returnSRTTimes(srtCBR1Average_T16,indexesActionsByType_T16, "instantaneous"))
srtCBR1AverageInstantaneous <- append(srtCBR1AverageInstantaneous,returnSRTTimes(srtCBR1Average_T17,indexesActionsByType_T17, "instantaneous"))
srtCBR1AverageInstantaneous <- append(srtCBR1AverageInstantaneous,returnSRTTimes(srtCBR1Average_T18,indexesActionsByType_T18, "instantaneous"))
srtCBR1AverageInstantaneous <- append(srtCBR1AverageInstantaneous,returnSRTTimes(srtCBR1Average_T19,indexesActionsByType_T19, "instantaneous"))
srtCBR1AverageInstantaneous <- append(srtCBR1AverageInstantaneous,returnSRTTimes(srtCBR1Average_T20,indexesActionsByType_T20, "instantaneous"))
srtCBR1AverageInstantaneous <- append(srtCBR1AverageInstantaneous,returnSRTTimes(srtCBR1Average_T21,indexesActionsByType_T21, "instantaneous"))
srtCBR1AverageInstantaneous <- append(srtCBR1AverageInstantaneous,returnSRTTimes(srtCBR1Average_T22,indexesActionsByType_T22, "instantaneous"))
srtCBR1AverageInstantaneous <- append(srtCBR1AverageInstantaneous,returnSRTTimes(srtCBR1Average_T23,indexesActionsByType_T23, "instantaneous"))
srtCBR1AverageInstantaneous <- append(srtCBR1AverageInstantaneous,returnSRTTimes(srtCBR1Average_T24,indexesActionsByType_T24, "instantaneous"))
srtCBR1AverageInstantaneous <- append(srtCBR1AverageInstantaneous,returnSRTTimes(srtCBR1Average_T25,indexesActionsByType_T25, "instantaneous"))
srtCBR1AverageInstantaneous <- unlist(srtCBR1AverageInstantaneous, recursive = FALSE)

srtSampler1AverageInstantaneous <- list()
srtSampler1AverageInstantaneous <- append(srtSampler1AverageInstantaneous,returnSRTTimes(srtSampler1Average_T1,indexesActionsByType_T1, "instantaneous"))
srtSampler1AverageInstantaneous <- append(srtSampler1AverageInstantaneous,returnSRTTimes(srtSampler1Average_T2,indexesActionsByType_T2, "instantaneous"))
srtSampler1AverageInstantaneous <- append(srtSampler1AverageInstantaneous,returnSRTTimes(srtSampler1Average_T3,indexesActionsByType_T3, "instantaneous"))
srtSampler1AverageInstantaneous <- append(srtSampler1AverageInstantaneous,returnSRTTimes(srtSampler1Average_T4,indexesActionsByType_T4, "instantaneous"))
srtSampler1AverageInstantaneous <- append(srtSampler1AverageInstantaneous,returnSRTTimes(srtSampler1Average_T5,indexesActionsByType_T5, "instantaneous"))
srtSampler1AverageInstantaneous <- append(srtSampler1AverageInstantaneous,returnSRTTimes(srtSampler1Average_T6,indexesActionsByType_T6, "instantaneous"))
srtSampler1AverageInstantaneous <- append(srtSampler1AverageInstantaneous,returnSRTTimes(srtSampler1Average_T7,indexesActionsByType_T7, "instantaneous"))
srtSampler1AverageInstantaneous <- append(srtSampler1AverageInstantaneous,returnSRTTimes(srtSampler1Average_T8,indexesActionsByType_T8, "instantaneous"))
srtSampler1AverageInstantaneous <- append(srtSampler1AverageInstantaneous,returnSRTTimes(srtSampler1Average_T9,indexesActionsByType_T9, "instantaneous"))
srtSampler1AverageInstantaneous <- append(srtSampler1AverageInstantaneous,returnSRTTimes(srtSampler1Average_T10,indexesActionsByType_T10, "instantaneous"))
srtSampler1AverageInstantaneous <- append(srtSampler1AverageInstantaneous,returnSRTTimes(srtSampler1Average_T11,indexesActionsByType_T11, "instantaneous"))
srtSampler1AverageInstantaneous <- append(srtSampler1AverageInstantaneous,returnSRTTimes(srtSampler1Average_T12,indexesActionsByType_T12, "instantaneous"))
srtSampler1AverageInstantaneous <- append(srtSampler1AverageInstantaneous,returnSRTTimes(srtSampler1Average_T13,indexesActionsByType_T13, "instantaneous"))
srtSampler1AverageInstantaneous <- append(srtSampler1AverageInstantaneous,returnSRTTimes(srtSampler1Average_T14,indexesActionsByType_T14, "instantaneous"))
srtSampler1AverageInstantaneous <- append(srtSampler1AverageInstantaneous,returnSRTTimes(srtSampler1Average_T15,indexesActionsByType_T15, "instantaneous"))
srtSampler1AverageInstantaneous <- append(srtSampler1AverageInstantaneous,returnSRTTimes(srtSampler1Average_T16,indexesActionsByType_T16, "instantaneous"))
srtSampler1AverageInstantaneous <- append(srtSampler1AverageInstantaneous,returnSRTTimes(srtSampler1Average_T17,indexesActionsByType_T17, "instantaneous"))
srtSampler1AverageInstantaneous <- append(srtSampler1AverageInstantaneous,returnSRTTimes(srtSampler1Average_T18,indexesActionsByType_T18, "instantaneous"))
srtSampler1AverageInstantaneous <- append(srtSampler1AverageInstantaneous,returnSRTTimes(srtSampler1Average_T19,indexesActionsByType_T19, "instantaneous"))
srtSampler1AverageInstantaneous <- append(srtSampler1AverageInstantaneous,returnSRTTimes(srtSampler1Average_T20,indexesActionsByType_T20, "instantaneous"))
srtSampler1AverageInstantaneous <- append(srtSampler1AverageInstantaneous,returnSRTTimes(srtSampler1Average_T21,indexesActionsByType_T21, "instantaneous"))
srtSampler1AverageInstantaneous <- append(srtSampler1AverageInstantaneous,returnSRTTimes(srtSampler1Average_T22,indexesActionsByType_T22, "instantaneous"))
srtSampler1AverageInstantaneous <- append(srtSampler1AverageInstantaneous,returnSRTTimes(srtSampler1Average_T23,indexesActionsByType_T23, "instantaneous"))
srtSampler1AverageInstantaneous <- append(srtSampler1AverageInstantaneous,returnSRTTimes(srtSampler1Average_T24,indexesActionsByType_T24, "instantaneous"))
srtSampler1AverageInstantaneous <- append(srtSampler1AverageInstantaneous,returnSRTTimes(srtSampler1Average_T25,indexesActionsByType_T25, "instantaneous"))
srtSampler1AverageInstantaneous <- unlist(srtSampler1AverageInstantaneous, recursive = FALSE)

srtSampler2AverageInstantaneous <- list()
srtSampler2AverageInstantaneous <- append(srtSampler2AverageInstantaneous,returnSRTTimes(srtSampler2Average_T1,indexesActionsByType_T1, "instantaneous"))
srtSampler2AverageInstantaneous <- append(srtSampler2AverageInstantaneous,returnSRTTimes(srtSampler2Average_T2,indexesActionsByType_T2, "instantaneous"))
srtSampler2AverageInstantaneous <- append(srtSampler2AverageInstantaneous,returnSRTTimes(srtSampler2Average_T3,indexesActionsByType_T3, "instantaneous"))
srtSampler2AverageInstantaneous <- append(srtSampler2AverageInstantaneous,returnSRTTimes(srtSampler2Average_T4,indexesActionsByType_T4, "instantaneous"))
srtSampler2AverageInstantaneous <- append(srtSampler2AverageInstantaneous,returnSRTTimes(srtSampler2Average_T5,indexesActionsByType_T5, "instantaneous"))
srtSampler2AverageInstantaneous <- append(srtSampler2AverageInstantaneous,returnSRTTimes(srtSampler2Average_T6,indexesActionsByType_T6, "instantaneous"))
srtSampler2AverageInstantaneous <- append(srtSampler2AverageInstantaneous,returnSRTTimes(srtSampler2Average_T7,indexesActionsByType_T7, "instantaneous"))
srtSampler2AverageInstantaneous <- append(srtSampler2AverageInstantaneous,returnSRTTimes(srtSampler2Average_T8,indexesActionsByType_T8, "instantaneous"))
srtSampler2AverageInstantaneous <- append(srtSampler2AverageInstantaneous,returnSRTTimes(srtSampler2Average_T9,indexesActionsByType_T9, "instantaneous"))
srtSampler2AverageInstantaneous <- append(srtSampler2AverageInstantaneous,returnSRTTimes(srtSampler2Average_T10,indexesActionsByType_T10, "instantaneous"))
srtSampler2AverageInstantaneous <- append(srtSampler2AverageInstantaneous,returnSRTTimes(srtSampler2Average_T11,indexesActionsByType_T11, "instantaneous"))
srtSampler2AverageInstantaneous <- append(srtSampler2AverageInstantaneous,returnSRTTimes(srtSampler2Average_T12,indexesActionsByType_T12, "instantaneous"))
srtSampler2AverageInstantaneous <- append(srtSampler2AverageInstantaneous,returnSRTTimes(srtSampler2Average_T13,indexesActionsByType_T13, "instantaneous"))
srtSampler2AverageInstantaneous <- append(srtSampler2AverageInstantaneous,returnSRTTimes(srtSampler2Average_T14,indexesActionsByType_T14, "instantaneous"))
srtSampler2AverageInstantaneous <- append(srtSampler2AverageInstantaneous,returnSRTTimes(srtSampler2Average_T15,indexesActionsByType_T15, "instantaneous"))
srtSampler2AverageInstantaneous <- append(srtSampler2AverageInstantaneous,returnSRTTimes(srtSampler2Average_T16,indexesActionsByType_T16, "instantaneous"))
srtSampler2AverageInstantaneous <- append(srtSampler2AverageInstantaneous,returnSRTTimes(srtSampler2Average_T17,indexesActionsByType_T17, "instantaneous"))
srtSampler2AverageInstantaneous <- append(srtSampler2AverageInstantaneous,returnSRTTimes(srtSampler2Average_T18,indexesActionsByType_T18, "instantaneous"))
srtSampler2AverageInstantaneous <- append(srtSampler2AverageInstantaneous,returnSRTTimes(srtSampler2Average_T19,indexesActionsByType_T19, "instantaneous"))
srtSampler2AverageInstantaneous <- append(srtSampler2AverageInstantaneous,returnSRTTimes(srtSampler2Average_T20,indexesActionsByType_T20, "instantaneous"))
srtSampler2AverageInstantaneous <- append(srtSampler2AverageInstantaneous,returnSRTTimes(srtSampler2Average_T21,indexesActionsByType_T21, "instantaneous"))
srtSampler2AverageInstantaneous <- append(srtSampler2AverageInstantaneous,returnSRTTimes(srtSampler2Average_T22,indexesActionsByType_T22, "instantaneous"))
srtSampler2AverageInstantaneous <- append(srtSampler2AverageInstantaneous,returnSRTTimes(srtSampler2Average_T23,indexesActionsByType_T23, "instantaneous"))
srtSampler2AverageInstantaneous <- append(srtSampler2AverageInstantaneous,returnSRTTimes(srtSampler2Average_T24,indexesActionsByType_T24, "instantaneous"))
srtSampler2AverageInstantaneous <- append(srtSampler2AverageInstantaneous,returnSRTTimes(srtSampler2Average_T25,indexesActionsByType_T25, "instantaneous"))
srtSampler2AverageInstantaneous <- unlist(srtSampler2AverageInstantaneous, recursive = FALSE)

ohNoMonCBR1Instantaneous <- overhead(mean(srtNoMonAverageInstantaneous,na.rm = TRUE),mean(srtCBR1AverageInstantaneous,na.rm = TRUE))
ohNoMonSampler1Instantaneous <- overhead(mean(srtNoMonAverageInstantaneous,na.rm = TRUE),mean(srtSampler1AverageInstantaneous,na.rm = TRUE))
ohNoMonSampler2Instantaneous <- overhead(mean(srtNoMonAverageInstantaneous,na.rm = TRUE),mean(srtSampler2AverageInstantaneous,na.rm = TRUE))


cat("ohNoMonCBR1Instantaneous: ", ohNoMonCBR1Instantaneous, "%\n")

cat("ohNoMonSampler1Instantaneous: ", ohNoMonSampler1Instantaneous, "%\n")

cat("ohNoMonSampler2Instantaneous: ", ohNoMonSampler2Instantaneous, "%\n")
